// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package prepaymentencapsulation

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandCmdEncapsulation cc.CommandID = 0x01

func init() {
	gob.Register(CmdEncapsulation{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x41),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewCmdEncapsulation)
}

func NewCmdEncapsulation() cc.Command {
	return &CmdEncapsulation{}
}

// <no value>
type CmdEncapsulation struct {
	Data []byte
}

func (cmd CmdEncapsulation) CommandClassID() cc.CommandClassID {
	return 0x41
}

func (cmd CmdEncapsulation) CommandID() cc.CommandID {
	return CommandCmdEncapsulation
}

func (cmd CmdEncapsulation) CommandIDString() string {
	return "CMD_ENCAPSULATION"
}

func (cmd *CmdEncapsulation) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return nil
	}

	cmd.Data = payload[i:]

	return nil
}

func (cmd *CmdEncapsulation) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.Data...)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
