// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package barrieroperator

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandSignalSupportedGet cc.CommandID = 0x04

func init() {
	gob.Register(SignalSupportedGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x66),
		Command:      cc.CommandID(0x04),
		Version:      1,
	}, NewSignalSupportedGet)
}

func NewSignalSupportedGet() cc.Command {
	return &SignalSupportedGet{}
}

// <no value>
type SignalSupportedGet struct {
}

func (cmd SignalSupportedGet) CommandClassID() cc.CommandClassID {
	return 0x66
}

func (cmd SignalSupportedGet) CommandID() cc.CommandID {
	return CommandSignalSupportedGet
}

func (cmd SignalSupportedGet) CommandIDString() string {
	return "BARRIER_OPERATOR_SIGNAL_SUPPORTED_GET"
}

func (cmd *SignalSupportedGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *SignalSupportedGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
