// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementbasicv2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandLearnModeSet cc.CommandID = 0x01

func init() {
	gob.Register(LearnModeSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x4D),
		Command:      cc.CommandID(0x01),
		Version:      2,
	}, NewLearnModeSet)
}

func NewLearnModeSet() cc.Command {
	return &LearnModeSet{}
}

// <no value>
type LearnModeSet struct {
	SeqNo byte

	Properties1 struct {
		ReturnInterviewStatus bool
	}

	Mode byte
}

func (cmd LearnModeSet) CommandClassID() cc.CommandClassID {
	return 0x4D
}

func (cmd LearnModeSet) CommandID() cc.CommandID {
	return CommandLearnModeSet
}

func (cmd LearnModeSet) CommandIDString() string {
	return "LEARN_MODE_SET"
}

func (cmd *LearnModeSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.ReturnInterviewStatus = payload[i]&0x01 == 0x01

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Mode = payload[i]
	i++

	return nil
}

func (cmd *LearnModeSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	{
		var val byte

		if cmd.Properties1.ReturnInterviewStatus {
			val |= byte(0x01) // flip bits on
		} else {
			val &= ^byte(0x01) // flip bits off
		}

		payload = append(payload, val)
	}

	payload = append(payload, cmd.Mode)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
