// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementinclusion

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandReturnRouteAssign cc.CommandID = 0x0D

func init() {
	gob.Register(ReturnRouteAssign{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x34),
		Command:      cc.CommandID(0x0D),
		Version:      1,
	}, NewReturnRouteAssign)
}

func NewReturnRouteAssign() cc.Command {
	return &ReturnRouteAssign{}
}

// <no value>
type ReturnRouteAssign struct {
	SeqNo byte

	SourceNodeId byte

	DestinationNodeId byte
}

func (cmd ReturnRouteAssign) CommandClassID() cc.CommandClassID {
	return 0x34
}

func (cmd ReturnRouteAssign) CommandID() cc.CommandID {
	return CommandReturnRouteAssign
}

func (cmd ReturnRouteAssign) CommandIDString() string {
	return "RETURN_ROUTE_ASSIGN"
}

func (cmd *ReturnRouteAssign) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SourceNodeId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.DestinationNodeId = payload[i]
	i++

	return nil
}

func (cmd *ReturnRouteAssign) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	payload = append(payload, cmd.SourceNodeId)

	payload = append(payload, cmd.DestinationNodeId)

	return
}
