// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package soundswitch

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandTonesNumberGet cc.CommandID = 0x01

func init() {
	gob.Register(TonesNumberGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x79),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewTonesNumberGet)
}

func NewTonesNumberGet() cc.Command {
	return &TonesNumberGet{}
}

// <no value>
type TonesNumberGet struct {
}

func (cmd TonesNumberGet) CommandClassID() cc.CommandClassID {
	return 0x79
}

func (cmd TonesNumberGet) CommandID() cc.CommandID {
	return CommandTonesNumberGet
}

func (cmd TonesNumberGet) CommandIDString() string {
	return "SOUND_SWITCH_TONES_NUMBER_GET"
}

func (cmd *TonesNumberGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *TonesNumberGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
