// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package tariffconfig

import (
	"encoding/binary"
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandTariffTblSet cc.CommandID = 0x02

func init() {
	gob.Register(TariffTblSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x4A),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewTariffTblSet)
}

func NewTariffTblSet() cc.Command {
	return &TariffTblSet{}
}

// <no value>
type TariffTblSet struct {
	RateParameterSetId byte

	Properties1 struct {
		TariffPrecision byte
	}

	TariffValue uint32
}

func (cmd TariffTblSet) CommandClassID() cc.CommandClassID {
	return 0x4A
}

func (cmd TariffTblSet) CommandID() cc.CommandID {
	return CommandTariffTblSet
}

func (cmd TariffTblSet) CommandIDString() string {
	return "TARIFF_TBL_SET"
}

func (cmd *TariffTblSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.RateParameterSetId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.TariffPrecision = (payload[i] & 0xE0) >> 5

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.TariffValue = binary.BigEndian.Uint32(payload[i : i+4])
	i += 4

	return nil
}

func (cmd *TariffTblSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.RateParameterSetId)

	{
		var val byte

		val |= (cmd.Properties1.TariffPrecision << byte(5)) & byte(0xE0)

		payload = append(payload, val)
	}

	{
		buf := make([]byte, 4)
		binary.BigEndian.PutUint32(buf, cmd.TariffValue)
		payload = append(payload, buf...)
	}

	return
}
