// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package windowcovering

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandStartLevelChange cc.CommandID = 0x06

func init() {
	gob.Register(StartLevelChange{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x6A),
		Command:      cc.CommandID(0x06),
		Version:      1,
	}, NewStartLevelChange)
}

func NewStartLevelChange() cc.Command {
	return &StartLevelChange{}
}

// <no value>
type StartLevelChange struct {
	Properties1 struct {
		Res1 byte

		UpDown bool

		Res2 bool
	}

	ParameterId byte

	Duration byte
}

func (cmd StartLevelChange) CommandClassID() cc.CommandClassID {
	return 0x6A
}

func (cmd StartLevelChange) CommandID() cc.CommandID {
	return CommandStartLevelChange
}

func (cmd StartLevelChange) CommandIDString() string {
	return "WINDOW_COVERING_START_LEVEL_CHANGE"
}

func (cmd *StartLevelChange) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.Res1 = (payload[i] & 0x3F)

	cmd.Properties1.UpDown = payload[i]&0x40 == 0x40

	cmd.Properties1.Res2 = payload[i]&0x80 == 0x80

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ParameterId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Duration = payload[i]
	i++

	return nil
}

func (cmd *StartLevelChange) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		val |= (cmd.Properties1.Res1) & byte(0x3F)

		if cmd.Properties1.UpDown {
			val |= byte(0x40) // flip bits on
		} else {
			val &= ^byte(0x40) // flip bits off
		}

		if cmd.Properties1.Res2 {
			val |= byte(0x80) // flip bits on
		} else {
			val &= ^byte(0x80) // flip bits off
		}

		payload = append(payload, val)
	}

	payload = append(payload, cmd.ParameterId)

	payload = append(payload, cmd.Duration)

	return
}
