// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package securitypanelzone

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandNumberSupportedGet cc.CommandID = 0x01

func init() {
	gob.Register(NumberSupportedGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x2E),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewNumberSupportedGet)
}

func NewNumberSupportedGet() cc.Command {
	return &NumberSupportedGet{}
}

// <no value>
type NumberSupportedGet struct {
}

func (cmd NumberSupportedGet) CommandClassID() cc.CommandClassID {
	return 0x2E
}

func (cmd NumberSupportedGet) CommandID() cc.CommandID {
	return CommandNumberSupportedGet
}

func (cmd NumberSupportedGet) CommandIDString() string {
	return "SECURITY_PANEL_ZONE_NUMBER_SUPPORTED_GET"
}

func (cmd *NumberSupportedGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *NumberSupportedGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
