// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package scheduleentrylockv2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandEnableAllSet cc.CommandID = 0x02

func init() {
	gob.Register(EnableAllSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x4E),
		Command:      cc.CommandID(0x02),
		Version:      2,
	}, NewEnableAllSet)
}

func NewEnableAllSet() cc.Command {
	return &EnableAllSet{}
}

// <no value>
type EnableAllSet struct {
	Enabled byte
}

func (cmd EnableAllSet) CommandClassID() cc.CommandClassID {
	return 0x4E
}

func (cmd EnableAllSet) CommandID() cc.CommandID {
	return CommandEnableAllSet
}

func (cmd EnableAllSet) CommandIDString() string {
	return "SCHEDULE_ENTRY_LOCK_ENABLE_ALL_SET"
}

func (cmd *EnableAllSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Enabled = payload[i]
	i++

	return nil
}

func (cmd *EnableAllSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.Enabled)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
