// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package groupingname

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandReport cc.CommandID = 0x03

func init() {
	gob.Register(Report{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x7B),
		Command:      cc.CommandID(0x03),
		Version:      1,
	}, NewReport)
}

func NewReport() cc.Command {
	return &Report{}
}

// <no value>
type Report struct {
	GroupingIdentifier byte

	Properties1 struct {
		CharPresentation byte
	}

	GroupingName string
}

func (cmd Report) CommandClassID() cc.CommandClassID {
	return 0x7B
}

func (cmd Report) CommandID() cc.CommandID {
	return CommandReport
}

func (cmd Report) CommandIDString() string {
	return "GROUPING_NAME_REPORT"
}

func (cmd *Report) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.GroupingIdentifier = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.CharPresentation = (payload[i] & 0x07)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.GroupingName = string(payload[i : i+16])

	i += 16

	return nil
}

func (cmd *Report) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.GroupingIdentifier)

	{
		var val byte

		val |= (cmd.Properties1.CharPresentation) & byte(0x07)

		payload = append(payload, val)
	}

	if paramLen := len(cmd.GroupingName); paramLen > 16 {
		return nil, errors.New("Length overflow in array parameter GroupingName")
	}

	payload = append(payload, []byte(cmd.GroupingName)...)

	return
}
