// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementprimary

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandControllerChangeStatus cc.CommandID = 0x02

func init() {
	gob.Register(ControllerChangeStatus{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x54),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewControllerChangeStatus)
}

func NewControllerChangeStatus() cc.Command {
	return &ControllerChangeStatus{}
}

// <no value>
type ControllerChangeStatus struct {
	SeqNo byte

	Status byte

	NewNodeId byte

	NodeInfoLength byte

	Properties1 struct {
		ZWaveProtocolSpecificPart1 byte

		Listening bool
	}

	Properties2 struct {
		ZWaveProtocolSpecificPart2 byte

		Opt bool
	}

	BasicDeviceClass byte

	GenericDeviceClass byte

	SpecificDeviceClass byte

	CommandClass []byte
}

func (cmd ControllerChangeStatus) CommandClassID() cc.CommandClassID {
	return 0x54
}

func (cmd ControllerChangeStatus) CommandID() cc.CommandID {
	return CommandControllerChangeStatus
}

func (cmd ControllerChangeStatus) CommandIDString() string {
	return "CONTROLLER_CHANGE_STATUS"
}

func (cmd *ControllerChangeStatus) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Status = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	i++ // skipping over reserved bit

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NewNodeId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NodeInfoLength = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.ZWaveProtocolSpecificPart1 = (payload[i] & 0x7F)

	cmd.Properties1.Listening = payload[i]&0x80 == 0x80

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties2.ZWaveProtocolSpecificPart2 = (payload[i] & 0x7F)

	cmd.Properties2.Opt = payload[i]&0x80 == 0x80

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.BasicDeviceClass = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.GenericDeviceClass = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SpecificDeviceClass = payload[i]
	i++

	if len(payload) <= i {
		return nil
	}

	cmd.CommandClass = payload[i:]

	return nil
}

func (cmd *ControllerChangeStatus) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	payload = append(payload, cmd.Status)

	payload = append(payload, cmd.NewNodeId)

	payload = append(payload, cmd.NodeInfoLength)

	{
		var val byte

		val |= (cmd.Properties1.ZWaveProtocolSpecificPart1) & byte(0x7F)

		if cmd.Properties1.Listening {
			val |= byte(0x80) // flip bits on
		} else {
			val &= ^byte(0x80) // flip bits off
		}

		payload = append(payload, val)
	}

	{
		var val byte

		val |= (cmd.Properties2.ZWaveProtocolSpecificPart2) & byte(0x7F)

		if cmd.Properties2.Opt {
			val |= byte(0x80) // flip bits on
		} else {
			val &= ^byte(0x80) // flip bits off
		}

		payload = append(payload, val)
	}

	payload = append(payload, cmd.BasicDeviceClass)

	payload = append(payload, cmd.GenericDeviceClass)

	payload = append(payload, cmd.SpecificDeviceClass)

	payload = append(payload, cmd.CommandClass...)

	return
}
