// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package multichannelv4

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandAggregatedMembersGet cc.CommandID = 0x0E

func init() {
	gob.Register(AggregatedMembersGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x60),
		Command:      cc.CommandID(0x0E),
		Version:      4,
	}, NewAggregatedMembersGet)
}

func NewAggregatedMembersGet() cc.Command {
	return &AggregatedMembersGet{}
}

// <no value>
type AggregatedMembersGet struct {
	Properties1 struct {
		AggregatedEndPoint byte
	}
}

func (cmd AggregatedMembersGet) CommandClassID() cc.CommandClassID {
	return 0x60
}

func (cmd AggregatedMembersGet) CommandID() cc.CommandID {
	return CommandAggregatedMembersGet
}

func (cmd AggregatedMembersGet) CommandIDString() string {
	return "MULTI_CHANNEL_AGGREGATED_MEMBERS_GET"
}

func (cmd *AggregatedMembersGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.AggregatedEndPoint = (payload[i] & 0x7F)

	i += 1

	return nil
}

func (cmd *AggregatedMembersGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		val |= (cmd.Properties1.AggregatedEndPoint) & byte(0x7F)

		payload = append(payload, val)
	}

	return
}
