// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package basictariffinfo

import (
	"encoding/binary"
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandReport cc.CommandID = 0x02

func init() {
	gob.Register(Report{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x36),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewReport)
}

func NewReport() cc.Command {
	return &Report{}
}

// <no value>
type Report struct {
	Properties1 struct {
		TotalNoImportRates byte

		Dual bool
	}

	Properties2 struct {
		E1CurrentRateInUse byte
	}

	E1RateConsumptionRegister uint32

	E1TimeForNextRateHours byte

	E1TimeForNextRateMinutes byte

	E1TimeForNextRateSeconds byte

	Properties3 struct {
		E2CurrentRateInUse byte
	}

	E2RateConsumptionRegister uint32
}

func (cmd Report) CommandClassID() cc.CommandClassID {
	return 0x36
}

func (cmd Report) CommandID() cc.CommandID {
	return CommandReport
}

func (cmd Report) CommandIDString() string {
	return "BASIC_TARIFF_INFO_REPORT"
}

func (cmd *Report) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.TotalNoImportRates = (payload[i] & 0x0F)

	cmd.Properties1.Dual = payload[i]&0x80 == 0x80

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties2.E1CurrentRateInUse = (payload[i] & 0x0F)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.E1RateConsumptionRegister = binary.BigEndian.Uint32(payload[i : i+4])
	i += 4

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.E1TimeForNextRateHours = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.E1TimeForNextRateMinutes = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.E1TimeForNextRateSeconds = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties3.E2CurrentRateInUse = (payload[i] & 0x0F)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.E2RateConsumptionRegister = binary.BigEndian.Uint32(payload[i : i+4])
	i += 4

	return nil
}

func (cmd *Report) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		val |= (cmd.Properties1.TotalNoImportRates) & byte(0x0F)

		if cmd.Properties1.Dual {
			val |= byte(0x80) // flip bits on
		} else {
			val &= ^byte(0x80) // flip bits off
		}

		payload = append(payload, val)
	}

	{
		var val byte

		val |= (cmd.Properties2.E1CurrentRateInUse) & byte(0x0F)

		payload = append(payload, val)
	}

	{
		buf := make([]byte, 4)
		binary.BigEndian.PutUint32(buf, cmd.E1RateConsumptionRegister)
		payload = append(payload, buf...)
	}

	payload = append(payload, cmd.E1TimeForNextRateHours)

	payload = append(payload, cmd.E1TimeForNextRateMinutes)

	payload = append(payload, cmd.E1TimeForNextRateSeconds)

	{
		var val byte

		val |= (cmd.Properties3.E2CurrentRateInUse) & byte(0x0F)

		payload = append(payload, val)
	}

	{
		buf := make([]byte, 4)
		binary.BigEndian.PutUint32(buf, cmd.E2RateConsumptionRegister)
		payload = append(payload, buf...)
	}

	return
}
