// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package transportservice

import (
	"encoding/binary"
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandSubsequentFragment cc.CommandID = 0xE0

func init() {
	gob.Register(SubsequentFragment{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x55),
		Command:      cc.CommandID(0xE0),
		Version:      1,
	}, NewSubsequentFragment)
}

func NewSubsequentFragment() cc.Command {
	return &SubsequentFragment{}
}

// <no value>
type SubsequentFragment struct {
	Properties1 struct {
		DatagramSize1 byte
	}

	DatagramSize2 byte

	Properties2 struct {
		DatagramOffset1 byte

		SequenceNo byte
	}

	DatagramOffset2 byte

	Payload []byte

	Checksum uint16
}

func (cmd SubsequentFragment) CommandClassID() cc.CommandClassID {
	return 0x55
}

func (cmd SubsequentFragment) CommandID() cc.CommandID {
	return CommandSubsequentFragment
}

func (cmd SubsequentFragment) CommandIDString() string {
	return "COMMAND_SUBSEQUENT_FRAGMENT"
}

func (cmd *SubsequentFragment) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.DatagramSize1 = (payload[i] & 0x07)

	i += 1

	if len(payload) <= i {
		return nil // field is optional
	}

	cmd.DatagramSize2 = payload[i]
	i++

	if len(payload) <= i {
		return nil // field is optional
	}

	cmd.Properties2.DatagramOffset1 = (payload[i] & 0x07)

	cmd.Properties2.SequenceNo = (payload[i] & 0x78) >> 3

	i += 1

	if len(payload) <= i {
		return nil // field is optional
	}

	cmd.DatagramOffset2 = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Payload = payload[i : len(payload)-2]
	i += len(cmd.Payload)

	cmd.Checksum = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	return nil
}

func (cmd *SubsequentFragment) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		val |= (cmd.Properties1.DatagramSize1) & byte(0x07)

		payload = append(payload, val)
	}

	payload = append(payload, cmd.DatagramSize2)

	{
		var val byte

		val |= (cmd.Properties2.DatagramOffset1) & byte(0x07)

		val |= (cmd.Properties2.SequenceNo << byte(3)) & byte(0x78)

		payload = append(payload, val)
	}

	payload = append(payload, cmd.DatagramOffset2)

	payload = append(payload, cmd.Payload...)

	{
		buf := make([]byte, 2)
		binary.BigEndian.PutUint16(buf, cmd.Checksum)
		payload = append(payload, buf...)
	}

	return
}
