// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package avcontentdirectorymd

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandAvContentBrowseMdReport cc.CommandID = 0x02

func init() {
	gob.Register(AvContentBrowseMdReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x95),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewAvContentBrowseMdReport)
}

func NewAvContentBrowseMdReport() cc.Command {
	return &AvContentBrowseMdReport{}
}

// <no value>
type AvContentBrowseMdReport struct {
}

func (cmd AvContentBrowseMdReport) CommandClassID() cc.CommandClassID {
	return 0x95
}

func (cmd AvContentBrowseMdReport) CommandID() cc.CommandID {
	return CommandAvContentBrowseMdReport
}

func (cmd AvContentBrowseMdReport) CommandIDString() string {
	return "AV_CONTENT_BROWSE_MD_REPORT"
}

func (cmd *AvContentBrowseMdReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *AvContentBrowseMdReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
