// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package avcontentdirectorymd

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandAvContentBrowseMdChildCountReport cc.CommandID = 0x06

func init() {
	gob.Register(AvContentBrowseMdChildCountReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x95),
		Command:      cc.CommandID(0x06),
		Version:      1,
	}, NewAvContentBrowseMdChildCountReport)
}

func NewAvContentBrowseMdChildCountReport() cc.Command {
	return &AvContentBrowseMdChildCountReport{}
}

// <no value>
type AvContentBrowseMdChildCountReport struct {
}

func (cmd AvContentBrowseMdChildCountReport) CommandClassID() cc.CommandClassID {
	return 0x95
}

func (cmd AvContentBrowseMdChildCountReport) CommandID() cc.CommandID {
	return CommandAvContentBrowseMdChildCountReport
}

func (cmd AvContentBrowseMdChildCountReport) CommandIDString() string {
	return "AV_CONTENT_BROWSE_MD_CHILD_COUNT_REPORT"
}

func (cmd *AvContentBrowseMdChildCountReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *AvContentBrowseMdChildCountReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
