// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package avcontentdirectorymd

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandAvMatchItemToRendererMdGet cc.CommandID = 0x07

func init() {
	gob.Register(AvMatchItemToRendererMdGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x95),
		Command:      cc.CommandID(0x07),
		Version:      1,
	}, NewAvMatchItemToRendererMdGet)
}

func NewAvMatchItemToRendererMdGet() cc.Command {
	return &AvMatchItemToRendererMdGet{}
}

// <no value>
type AvMatchItemToRendererMdGet struct {
}

func (cmd AvMatchItemToRendererMdGet) CommandClassID() cc.CommandClassID {
	return 0x95
}

func (cmd AvMatchItemToRendererMdGet) CommandID() cc.CommandID {
	return CommandAvMatchItemToRendererMdGet
}

func (cmd AvMatchItemToRendererMdGet) CommandIDString() string {
	return "AV_MATCH_ITEM_TO_RENDERER_MD_GET"
}

func (cmd *AvMatchItemToRendererMdGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *AvMatchItemToRendererMdGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
