// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package avcontentdirectorymd

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandAvMatchItemToRendererMdReport cc.CommandID = 0x08

func init() {
	gob.Register(AvMatchItemToRendererMdReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x95),
		Command:      cc.CommandID(0x08),
		Version:      1,
	}, NewAvMatchItemToRendererMdReport)
}

func NewAvMatchItemToRendererMdReport() cc.Command {
	return &AvMatchItemToRendererMdReport{}
}

// <no value>
type AvMatchItemToRendererMdReport struct {
}

func (cmd AvMatchItemToRendererMdReport) CommandClassID() cc.CommandClassID {
	return 0x95
}

func (cmd AvMatchItemToRendererMdReport) CommandID() cc.CommandID {
	return CommandAvMatchItemToRendererMdReport
}

func (cmd AvMatchItemToRendererMdReport) CommandIDString() string {
	return "AV_MATCH_ITEM_TO_RENDERER_MD_REPORT"
}

func (cmd *AvMatchItemToRendererMdReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *AvMatchItemToRendererMdReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
