// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package security2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandKexFail cc.CommandID = 0x07

func init() {
	gob.Register(KexFail{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x9F),
		Command:      cc.CommandID(0x07),
		Version:      1,
	}, NewKexFail)
}

func NewKexFail() cc.Command {
	return &KexFail{}
}

// <no value>
type KexFail struct {
	KexFailType byte
}

func (cmd KexFail) CommandClassID() cc.CommandClassID {
	return 0x9F
}

func (cmd KexFail) CommandID() cc.CommandID {
	return CommandKexFail
}

func (cmd KexFail) CommandIDString() string {
	return "KEX_FAIL"
}

func (cmd *KexFail) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.KexFailType = payload[i]
	i++

	return nil
}

func (cmd *KexFail) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.KexFailType)

	return
}
