// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package security2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandNonceGet cc.CommandID = 0x01

func init() {
	gob.Register(NonceGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x9F),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewNonceGet)
}

func NewNonceGet() cc.Command {
	return &NonceGet{}
}

// <no value>
type NonceGet struct {
	SequenceNumber byte
}

func (cmd NonceGet) CommandClassID() cc.CommandClassID {
	return 0x9F
}

func (cmd NonceGet) CommandID() cc.CommandID {
	return CommandNonceGet
}

func (cmd NonceGet) CommandIDString() string {
	return "SECURITY_2_NONCE_GET"
}

func (cmd *NonceGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SequenceNumber = payload[i]
	i++

	return nil
}

func (cmd *NonceGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SequenceNumber)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
