// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package security2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandNonceReport cc.CommandID = 0x02

func init() {
	gob.Register(NonceReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x9F),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewNonceReport)
}

func NewNonceReport() cc.Command {
	return &NonceReport{}
}

// <no value>
type NonceReport struct {
	SequenceNumber byte

	Properties1 struct {
		Sos bool

		Mos bool
	}

	ReceiversEntropyInput []byte
}

func (cmd NonceReport) CommandClassID() cc.CommandClassID {
	return 0x9F
}

func (cmd NonceReport) CommandID() cc.CommandID {
	return CommandNonceReport
}

func (cmd NonceReport) CommandIDString() string {
	return "SECURITY_2_NONCE_REPORT"
}

func (cmd *NonceReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SequenceNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.Sos = payload[i]&0x01 == 0x01

	cmd.Properties1.Mos = payload[i]&0x02 == 0x02

	i += 1

	if len(payload) <= i {
		return nil
	}

	cmd.ReceiversEntropyInput = payload[i:]

	return nil
}

func (cmd *NonceReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SequenceNumber)

	{
		var val byte

		if cmd.Properties1.Sos {
			val |= byte(0x01) // flip bits on
		} else {
			val &= ^byte(0x01) // flip bits off
		}

		if cmd.Properties1.Mos {
			val |= byte(0x02) // flip bits on
		} else {
			val &= ^byte(0x02) // flip bits off
		}

		payload = append(payload, val)
	}

	payload = append(payload, cmd.ReceiversEntropyInput...)

	return
}
