// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package security2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandTransferEnd cc.CommandID = 0x0C

func init() {
	gob.Register(TransferEnd{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x9F),
		Command:      cc.CommandID(0x0C),
		Version:      1,
	}, NewTransferEnd)
}

func NewTransferEnd() cc.Command {
	return &TransferEnd{}
}

// <no value>
type TransferEnd struct {
	Properties1 struct {
		KeyRequestComplete bool

		KeyVerified bool
	}
}

func (cmd TransferEnd) CommandClassID() cc.CommandClassID {
	return 0x9F
}

func (cmd TransferEnd) CommandID() cc.CommandID {
	return CommandTransferEnd
}

func (cmd TransferEnd) CommandIDString() string {
	return "SECURITY_2_TRANSFER_END"
}

func (cmd *TransferEnd) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.KeyRequestComplete = payload[i]&0x01 == 0x01

	cmd.Properties1.KeyVerified = payload[i]&0x02 == 0x02

	i += 1

	return nil
}

func (cmd *TransferEnd) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		if cmd.Properties1.KeyRequestComplete {
			val |= byte(0x01) // flip bits on
		} else {
			val &= ^byte(0x01) // flip bits off
		}

		if cmd.Properties1.KeyVerified {
			val |= byte(0x02) // flip bits on
		} else {
			val &= ^byte(0x02) // flip bits off
		}

		payload = append(payload, val)
	}

	return
}
