// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementbasic

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandLearnModeSetStatus cc.CommandID = 0x02

func init() {
	gob.Register(LearnModeSetStatus{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x4D),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewLearnModeSetStatus)
}

func NewLearnModeSetStatus() cc.Command {
	return &LearnModeSetStatus{}
}

// <no value>
type LearnModeSetStatus struct {
	SeqNo byte

	Status byte

	NewNodeId byte
}

func (cmd LearnModeSetStatus) CommandClassID() cc.CommandClassID {
	return 0x4D
}

func (cmd LearnModeSetStatus) CommandID() cc.CommandID {
	return CommandLearnModeSetStatus
}

func (cmd LearnModeSetStatus) CommandIDString() string {
	return "LEARN_MODE_SET_STATUS"
}

func (cmd *LearnModeSetStatus) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Status = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	i++ // skipping over reserved bit

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NewNodeId = payload[i]
	i++

	return nil
}

func (cmd *LearnModeSetStatus) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	payload = append(payload, cmd.Status)

	payload = append(payload, cmd.NewNodeId)

	return
}
