// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementbasic

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandNodeInformationSend cc.CommandID = 0x05

func init() {
	gob.Register(NodeInformationSend{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x4D),
		Command:      cc.CommandID(0x05),
		Version:      1,
	}, NewNodeInformationSend)
}

func NewNodeInformationSend() cc.Command {
	return &NodeInformationSend{}
}

// <no value>
type NodeInformationSend struct {
	SeqNo byte

	DestinationNodeId byte

	TxOptions []byte
}

func (cmd NodeInformationSend) CommandClassID() cc.CommandClassID {
	return 0x4D
}

func (cmd NodeInformationSend) CommandID() cc.CommandID {
	return CommandNodeInformationSend
}

func (cmd NodeInformationSend) CommandIDString() string {
	return "NODE_INFORMATION_SEND"
}

func (cmd *NodeInformationSend) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	i++ // skipping over reserved bit

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.DestinationNodeId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.TxOptions = payload[i:]

	return nil
}

func (cmd *NodeInformationSend) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	payload = append(payload, cmd.DestinationNodeId)

	payload = append(payload, cmd.TxOptions...)

	return
}
