// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package entrycontrol

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandEventSupportedGet cc.CommandID = 0x04

func init() {
	gob.Register(EventSupportedGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x6F),
		Command:      cc.CommandID(0x04),
		Version:      1,
	}, NewEventSupportedGet)
}

func NewEventSupportedGet() cc.Command {
	return &EventSupportedGet{}
}

// <no value>
type EventSupportedGet struct {
}

func (cmd EventSupportedGet) CommandClassID() cc.CommandClassID {
	return 0x6F
}

func (cmd EventSupportedGet) CommandID() cc.CommandID {
	return CommandEventSupportedGet
}

func (cmd EventSupportedGet) CommandIDString() string {
	return "ENTRY_CONTROL_EVENT_SUPPORTED_GET"
}

func (cmd *EventSupportedGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *EventSupportedGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
