// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package entrycontrol

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandEventSupportedReport cc.CommandID = 0x05

func init() {
	gob.Register(EventSupportedReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x6F),
		Command:      cc.CommandID(0x05),
		Version:      1,
	}, NewEventSupportedReport)
}

func NewEventSupportedReport() cc.Command {
	return &EventSupportedReport{}
}

// <no value>
type EventSupportedReport struct {
	Properties1 struct {
		DataTypeSupportedBitMaskLength byte
	}

	DataTypeSupportedBitMask []byte

	Properties2 struct {
		EventSupportedBitMaskLength byte
	}

	EventTypeSupportedBitMask []byte

	KeyCachedSizeSupportedMinimum byte

	KeyCachedSizeSupportedMaximum byte

	KeyCachedTimeoutSupportedMinimum byte

	KeyCachedTimeoutSupportedMaximum byte
}

func (cmd EventSupportedReport) CommandClassID() cc.CommandClassID {
	return 0x6F
}

func (cmd EventSupportedReport) CommandID() cc.CommandID {
	return CommandEventSupportedReport
}

func (cmd EventSupportedReport) CommandIDString() string {
	return "ENTRY_CONTROL_EVENT_SUPPORTED_REPORT"
}

func (cmd *EventSupportedReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.DataTypeSupportedBitMaskLength = (payload[i] & 0x03)

	i += 1

	if len(payload) <= i {
		return nil // field is optional
	}

	cmd.DataTypeSupportedBitMask = payload[i:]

	if len(payload) <= i {
		return nil // field is optional
	}

	cmd.Properties2.EventSupportedBitMaskLength = (payload[i] & 0x1F)

	i += 1

	if len(payload) <= i {
		return nil // field is optional
	}

	cmd.EventTypeSupportedBitMask = payload[i:]

	if len(payload) <= i {
		return nil // field is optional
	}

	cmd.KeyCachedSizeSupportedMinimum = payload[i]
	i++

	if len(payload) <= i {
		return nil // field is optional
	}

	cmd.KeyCachedSizeSupportedMaximum = payload[i]
	i++

	if len(payload) <= i {
		return nil // field is optional
	}

	cmd.KeyCachedTimeoutSupportedMinimum = payload[i]
	i++

	if len(payload) <= i {
		return nil // field is optional
	}

	cmd.KeyCachedTimeoutSupportedMaximum = payload[i]
	i++

	return nil
}

func (cmd *EventSupportedReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		val |= (cmd.Properties1.DataTypeSupportedBitMaskLength) & byte(0x03)

		payload = append(payload, val)
	}

	payload = append(payload, cmd.DataTypeSupportedBitMask...)

	{
		var val byte

		val |= (cmd.Properties2.EventSupportedBitMaskLength) & byte(0x1F)

		payload = append(payload, val)
	}

	payload = append(payload, cmd.EventTypeSupportedBitMask...)

	payload = append(payload, cmd.KeyCachedSizeSupportedMinimum)

	payload = append(payload, cmd.KeyCachedSizeSupportedMaximum)

	payload = append(payload, cmd.KeyCachedTimeoutSupportedMinimum)

	payload = append(payload, cmd.KeyCachedTimeoutSupportedMaximum)

	return
}
