// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package entrycontrol

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandNotification cc.CommandID = 0x01

func init() {
	gob.Register(Notification{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x6F),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewNotification)
}

func NewNotification() cc.Command {
	return &Notification{}
}

// <no value>
type Notification struct {
	SequenceNumber byte

	Properties1 struct {
		DataType byte
	}

	EventType byte

	EventDataLength byte

	EventData []byte
}

func (cmd Notification) CommandClassID() cc.CommandClassID {
	return 0x6F
}

func (cmd Notification) CommandID() cc.CommandID {
	return CommandNotification
}

func (cmd Notification) CommandIDString() string {
	return "ENTRY_CONTROL_NOTIFICATION"
}

func (cmd *Notification) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SequenceNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.DataType = (payload[i] & 0x03)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.EventType = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.EventDataLength = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	{
		length := (payload[3+2]) & 0xFF
		cmd.EventData = payload[i : i+int(length)]
		i += int(length)
	}

	return nil
}

func (cmd *Notification) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SequenceNumber)

	{
		var val byte

		val |= (cmd.Properties1.DataType) & byte(0x03)

		payload = append(payload, val)
	}

	payload = append(payload, cmd.EventType)

	payload = append(payload, cmd.EventDataLength)

	if cmd.EventData != nil && len(cmd.EventData) > 0 {
		payload = append(payload, cmd.EventData...)
	}

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
