// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package multichannelv3

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandCapabilityGet cc.CommandID = 0x09

func init() {
	gob.Register(CapabilityGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x60),
		Command:      cc.CommandID(0x09),
		Version:      3,
	}, NewCapabilityGet)
}

func NewCapabilityGet() cc.Command {
	return &CapabilityGet{}
}

// <no value>
type CapabilityGet struct {
	Properties1 struct {
		EndPoint byte
	}
}

func (cmd CapabilityGet) CommandClassID() cc.CommandClassID {
	return 0x60
}

func (cmd CapabilityGet) CommandID() cc.CommandID {
	return CommandCapabilityGet
}

func (cmd CapabilityGet) CommandIDString() string {
	return "MULTI_CHANNEL_CAPABILITY_GET"
}

func (cmd *CapabilityGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.EndPoint = (payload[i] & 0x7F)

	i += 1

	return nil
}

func (cmd *CapabilityGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		val |= (cmd.Properties1.EndPoint) & byte(0x7F)

		payload = append(payload, val)
	}

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
