// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package thermostatheating

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandModeSet cc.CommandID = 0x01

func init() {
	gob.Register(ModeSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x38),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewModeSet)
}

func NewModeSet() cc.Command {
	return &ModeSet{}
}

// <no value>
type ModeSet struct {
	Mode byte
}

func (cmd ModeSet) CommandClassID() cc.CommandClassID {
	return 0x38
}

func (cmd ModeSet) CommandID() cc.CommandID {
	return CommandModeSet
}

func (cmd ModeSet) CommandIDString() string {
	return "THERMOSTAT_HEATING_MODE_SET"
}

func (cmd *ModeSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Mode = payload[i]
	i++

	return nil
}

func (cmd *ModeSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.Mode)

	return
}
