// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package thermostatheating

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandRelayStatusGet cc.CommandID = 0x09

func init() {
	gob.Register(RelayStatusGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x38),
		Command:      cc.CommandID(0x09),
		Version:      1,
	}, NewRelayStatusGet)
}

func NewRelayStatusGet() cc.Command {
	return &RelayStatusGet{}
}

// <no value>
type RelayStatusGet struct {
}

func (cmd RelayStatusGet) CommandClassID() cc.CommandClassID {
	return 0x38
}

func (cmd RelayStatusGet) CommandID() cc.CommandID {
	return CommandRelayStatusGet
}

func (cmd RelayStatusGet) CommandIDString() string {
	return "THERMOSTAT_HEATING_RELAY_STATUS_GET"
}

func (cmd *RelayStatusGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *RelayStatusGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
