// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package thermostatheating

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandSetpointGet cc.CommandID = 0x05

func init() {
	gob.Register(SetpointGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x38),
		Command:      cc.CommandID(0x05),
		Version:      1,
	}, NewSetpointGet)
}

func NewSetpointGet() cc.Command {
	return &SetpointGet{}
}

// <no value>
type SetpointGet struct {
	SetpointNr byte
}

func (cmd SetpointGet) CommandClassID() cc.CommandClassID {
	return 0x38
}

func (cmd SetpointGet) CommandID() cc.CommandID {
	return CommandSetpointGet
}

func (cmd SetpointGet) CommandIDString() string {
	return "THERMOSTAT_HEATING_SETPOINT_GET"
}

func (cmd *SetpointGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SetpointNr = payload[i]
	i++

	return nil
}

func (cmd *SetpointGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SetpointNr)

	return
}
