// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package thermostatheating

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandTimedOffSet cc.CommandID = 0x11

func init() {
	gob.Register(TimedOffSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x38),
		Command:      cc.CommandID(0x11),
		Version:      1,
	}, NewTimedOffSet)
}

func NewTimedOffSet() cc.Command {
	return &TimedOffSet{}
}

// <no value>
type TimedOffSet struct {
	Minutes byte

	Hours byte
}

func (cmd TimedOffSet) CommandClassID() cc.CommandClassID {
	return 0x38
}

func (cmd TimedOffSet) CommandID() cc.CommandID {
	return CommandTimedOffSet
}

func (cmd TimedOffSet) CommandIDString() string {
	return "THERMOSTAT_HEATING_TIMED_OFF_SET"
}

func (cmd *TimedOffSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Minutes = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Hours = payload[i]
	i++

	return nil
}

func (cmd *TimedOffSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.Minutes)

	payload = append(payload, cmd.Hours)

	return
}
