// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package protectionv2

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandEcGet cc.CommandID = 0x07

func init() {
	gob.Register(EcGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x75),
		Command:      cc.CommandID(0x07),
		Version:      2,
	}, NewEcGet)
}

func NewEcGet() cc.Command {
	return &EcGet{}
}

// <no value>
type EcGet struct {
}

func (cmd EcGet) CommandClassID() cc.CommandClassID {
	return 0x75
}

func (cmd EcGet) CommandID() cc.CommandID {
	return CommandEcGet
}

func (cmd EcGet) CommandIDString() string {
	return "PROTECTION_EC_GET"
}

func (cmd *EcGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *EcGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
