// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package protectionv2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandEcReport cc.CommandID = 0x08

func init() {
	gob.Register(EcReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x75),
		Command:      cc.CommandID(0x08),
		Version:      2,
	}, NewEcReport)
}

func NewEcReport() cc.Command {
	return &EcReport{}
}

// <no value>
type EcReport struct {
	NodeId byte
}

func (cmd EcReport) CommandClassID() cc.CommandClassID {
	return 0x75
}

func (cmd EcReport) CommandID() cc.CommandID {
	return CommandEcReport
}

func (cmd EcReport) CommandIDString() string {
	return "PROTECTION_EC_REPORT"
}

func (cmd *EcReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NodeId = payload[i]
	i++

	return nil
}

func (cmd *EcReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.NodeId)

	return
}
