// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package hail

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandHail cc.CommandID = 0x01

func init() {
	gob.Register(Hail{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x82),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewHail)
}

func NewHail() cc.Command {
	return &Hail{}
}

// <no value>
type Hail struct {
}

func (cmd Hail) CommandClassID() cc.CommandClassID {
	return 0x82
}

func (cmd Hail) CommandID() cc.CommandID {
	return CommandHail
}

func (cmd Hail) CommandIDString() string {
	return "HAIL"
}

func (cmd *Hail) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *Hail) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
