// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package chimneyfan

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandAlarmTempGet cc.CommandID = 0x0E

func init() {
	gob.Register(AlarmTempGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x2A),
		Command:      cc.CommandID(0x0E),
		Version:      1,
	}, NewAlarmTempGet)
}

func NewAlarmTempGet() cc.Command {
	return &AlarmTempGet{}
}

// <no value>
type AlarmTempGet struct {
}

func (cmd AlarmTempGet) CommandClassID() cc.CommandClassID {
	return 0x2A
}

func (cmd AlarmTempGet) CommandID() cc.CommandID {
	return CommandAlarmTempGet
}

func (cmd AlarmTempGet) CommandIDString() string {
	return "CHIMNEY_FAN_ALARM_TEMP_GET"
}

func (cmd *AlarmTempGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *AlarmTempGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
