// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package chimneyfan

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandAlarmStatusGet cc.CommandID = 0x23

func init() {
	gob.Register(AlarmStatusGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x2A),
		Command:      cc.CommandID(0x23),
		Version:      1,
	}, NewAlarmStatusGet)
}

func NewAlarmStatusGet() cc.Command {
	return &AlarmStatusGet{}
}

// <no value>
type AlarmStatusGet struct {
}

func (cmd AlarmStatusGet) CommandClassID() cc.CommandClassID {
	return 0x2A
}

func (cmd AlarmStatusGet) CommandID() cc.CommandID {
	return CommandAlarmStatusGet
}

func (cmd AlarmStatusGet) CommandIDString() string {
	return "CHIMNEY_FAN_ALARM_STATUS_GET"
}

func (cmd *AlarmStatusGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *AlarmStatusGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
