// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package chimneyfan

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandMinSpeedGet cc.CommandID = 0x26

func init() {
	gob.Register(MinSpeedGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x2A),
		Command:      cc.CommandID(0x26),
		Version:      1,
	}, NewMinSpeedGet)
}

func NewMinSpeedGet() cc.Command {
	return &MinSpeedGet{}
}

// <no value>
type MinSpeedGet struct {
}

func (cmd MinSpeedGet) CommandClassID() cc.CommandClassID {
	return 0x2A
}

func (cmd MinSpeedGet) CommandID() cc.CommandID {
	return CommandMinSpeedGet
}

func (cmd MinSpeedGet) CommandIDString() string {
	return "CHIMNEY_FAN_MIN_SPEED_GET"
}

func (cmd *MinSpeedGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *MinSpeedGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
