// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package chimneyfan

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandSetupGet cc.CommandID = 0x1A

func init() {
	gob.Register(SetupGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x2A),
		Command:      cc.CommandID(0x1A),
		Version:      1,
	}, NewSetupGet)
}

func NewSetupGet() cc.Command {
	return &SetupGet{}
}

// <no value>
type SetupGet struct {
}

func (cmd SetupGet) CommandClassID() cc.CommandClassID {
	return 0x2A
}

func (cmd SetupGet) CommandID() cc.CommandID {
	return CommandSetupGet
}

func (cmd SetupGet) CommandIDString() string {
	return "CHIMNEY_FAN_SETUP_GET"
}

func (cmd *SetupGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *SetupGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
