// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package chimneyfan

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandSpeedGet cc.CommandID = 0x05

func init() {
	gob.Register(SpeedGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x2A),
		Command:      cc.CommandID(0x05),
		Version:      1,
	}, NewSpeedGet)
}

func NewSpeedGet() cc.Command {
	return &SpeedGet{}
}

// <no value>
type SpeedGet struct {
}

func (cmd SpeedGet) CommandClassID() cc.CommandClassID {
	return 0x2A
}

func (cmd SpeedGet) CommandID() cc.CommandID {
	return CommandSpeedGet
}

func (cmd SpeedGet) CommandIDString() string {
	return "CHIMNEY_FAN_SPEED_GET"
}

func (cmd *SpeedGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *SpeedGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
