// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package chimneyfan

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandStatusGet cc.CommandID = 0x1D

func init() {
	gob.Register(StatusGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x2A),
		Command:      cc.CommandID(0x1D),
		Version:      1,
	}, NewStatusGet)
}

func NewStatusGet() cc.Command {
	return &StatusGet{}
}

// <no value>
type StatusGet struct {
}

func (cmd StatusGet) CommandClassID() cc.CommandClassID {
	return 0x2A
}

func (cmd StatusGet) CommandID() cc.CommandID {
	return CommandStatusGet
}

func (cmd StatusGet) CommandIDString() string {
	return "CHIMNEY_FAN_STATUS_GET"
}

func (cmd *StatusGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *StatusGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
