// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package chimneyfan

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandStopTempGet cc.CommandID = 0x0B

func init() {
	gob.Register(StopTempGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x2A),
		Command:      cc.CommandID(0x0B),
		Version:      1,
	}, NewStopTempGet)
}

func NewStopTempGet() cc.Command {
	return &StopTempGet{}
}

// <no value>
type StopTempGet struct {
}

func (cmd StopTempGet) CommandClassID() cc.CommandClassID {
	return 0x2A
}

func (cmd StopTempGet) CommandID() cc.CommandID {
	return CommandStopTempGet
}

func (cmd StopTempGet) CommandIDString() string {
	return "CHIMNEY_FAN_STOP_TEMP_GET"
}

func (cmd *StopTempGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *StopTempGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
