// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package mailbox

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandNodeFailing cc.CommandID = 0x06

func init() {
	gob.Register(NodeFailing{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x69),
		Command:      cc.CommandID(0x06),
		Version:      1,
	}, NewNodeFailing)
}

func NewNodeFailing() cc.Command {
	return &NodeFailing{}
}

// <no value>
type NodeFailing struct {
	QueueHandle byte
}

func (cmd NodeFailing) CommandClassID() cc.CommandClassID {
	return 0x69
}

func (cmd NodeFailing) CommandID() cc.CommandID {
	return CommandNodeFailing
}

func (cmd NodeFailing) CommandIDString() string {
	return "MAILBOX_NODE_FAILING"
}

func (cmd *NodeFailing) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.QueueHandle = payload[i]
	i++

	return nil
}

func (cmd *NodeFailing) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.QueueHandle)

	return
}
