// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementproxyv2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandNmMultiChannelCapabilityReport cc.CommandID = 0x08

func init() {
	gob.Register(NmMultiChannelCapabilityReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x52),
		Command:      cc.CommandID(0x08),
		Version:      2,
	}, NewNmMultiChannelCapabilityReport)
}

func NewNmMultiChannelCapabilityReport() cc.Command {
	return &NmMultiChannelCapabilityReport{}
}

// <no value>
type NmMultiChannelCapabilityReport struct {
	SeqNo byte

	Nodeid byte

	CommandClassLength byte

	Properties1 struct {
		EndPoint byte

		Res1 bool
	}

	GenericDeviceClass byte

	SpecificDeviceClass byte

	CommandClass []byte
}

func (cmd NmMultiChannelCapabilityReport) CommandClassID() cc.CommandClassID {
	return 0x52
}

func (cmd NmMultiChannelCapabilityReport) CommandID() cc.CommandID {
	return CommandNmMultiChannelCapabilityReport
}

func (cmd NmMultiChannelCapabilityReport) CommandIDString() string {
	return "NM_MULTI_CHANNEL_CAPABILITY_REPORT"
}

func (cmd *NmMultiChannelCapabilityReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Nodeid = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.CommandClassLength = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.EndPoint = (payload[i] & 0x7F)

	cmd.Properties1.Res1 = payload[i]&0x80 == 0x80

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.GenericDeviceClass = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SpecificDeviceClass = payload[i]
	i++

	if len(payload) <= i {
		return nil
	}

	cmd.CommandClass = payload[i:]

	return nil
}

func (cmd *NmMultiChannelCapabilityReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	payload = append(payload, cmd.Nodeid)

	payload = append(payload, cmd.CommandClassLength)

	{
		var val byte

		val |= (cmd.Properties1.EndPoint) & byte(0x7F)

		if cmd.Properties1.Res1 {
			val |= byte(0x80) // flip bits on
		} else {
			val &= ^byte(0x80) // flip bits off
		}

		payload = append(payload, val)
	}

	payload = append(payload, cmd.GenericDeviceClass)

	payload = append(payload, cmd.SpecificDeviceClass)

	payload = append(payload, cmd.CommandClass...)

	return
}
