// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementproxyv2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandNmMultiChannelEndPointGet cc.CommandID = 0x05

func init() {
	gob.Register(NmMultiChannelEndPointGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x52),
		Command:      cc.CommandID(0x05),
		Version:      2,
	}, NewNmMultiChannelEndPointGet)
}

func NewNmMultiChannelEndPointGet() cc.Command {
	return &NmMultiChannelEndPointGet{}
}

// <no value>
type NmMultiChannelEndPointGet struct {
	SeqNo byte

	Nodeid byte
}

func (cmd NmMultiChannelEndPointGet) CommandClassID() cc.CommandClassID {
	return 0x52
}

func (cmd NmMultiChannelEndPointGet) CommandID() cc.CommandID {
	return CommandNmMultiChannelEndPointGet
}

func (cmd NmMultiChannelEndPointGet) CommandIDString() string {
	return "NM_MULTI_CHANNEL_END_POINT_GET"
}

func (cmd *NmMultiChannelEndPointGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Nodeid = payload[i]
	i++

	return nil
}

func (cmd *NmMultiChannelEndPointGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	payload = append(payload, cmd.Nodeid)

	return
}
