// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package firmwareupdatemdv4

import (
	"encoding/binary"
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandFirmwareUpdateActivationSet cc.CommandID = 0x08

func init() {
	gob.Register(FirmwareUpdateActivationSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x7A),
		Command:      cc.CommandID(0x08),
		Version:      4,
	}, NewFirmwareUpdateActivationSet)
}

func NewFirmwareUpdateActivationSet() cc.Command {
	return &FirmwareUpdateActivationSet{}
}

// <no value>
type FirmwareUpdateActivationSet struct {
	ManufacturerId uint16

	FirmwareId uint16

	Checksum uint16

	FirmwareTarget byte
}

func (cmd FirmwareUpdateActivationSet) CommandClassID() cc.CommandClassID {
	return 0x7A
}

func (cmd FirmwareUpdateActivationSet) CommandID() cc.CommandID {
	return CommandFirmwareUpdateActivationSet
}

func (cmd FirmwareUpdateActivationSet) CommandIDString() string {
	return "FIRMWARE_UPDATE_ACTIVATION_SET"
}

func (cmd *FirmwareUpdateActivationSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ManufacturerId = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.FirmwareId = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Checksum = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.FirmwareTarget = payload[i]
	i++

	return nil
}

func (cmd *FirmwareUpdateActivationSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		buf := make([]byte, 2)
		binary.BigEndian.PutUint16(buf, cmd.ManufacturerId)
		payload = append(payload, buf...)
	}

	{
		buf := make([]byte, 2)
		binary.BigEndian.PutUint16(buf, cmd.FirmwareId)
		payload = append(payload, buf...)
	}

	{
		buf := make([]byte, 2)
		binary.BigEndian.PutUint16(buf, cmd.Checksum)
		payload = append(payload, buf...)
	}

	payload = append(payload, cmd.FirmwareTarget)

	return
}
