// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package dmx

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandAddressGet cc.CommandID = 0x02

func init() {
	gob.Register(AddressGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x65),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewAddressGet)
}

func NewAddressGet() cc.Command {
	return &AddressGet{}
}

// <no value>
type AddressGet struct {
}

func (cmd AddressGet) CommandClassID() cc.CommandClassID {
	return 0x65
}

func (cmd AddressGet) CommandID() cc.CommandID {
	return CommandAddressGet
}

func (cmd AddressGet) CommandIDString() string {
	return "DMX_ADDRESS_GET"
}

func (cmd *AddressGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *AddressGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
