// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package dmx

import (
	"encoding/binary"
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandCapabilityReport cc.CommandID = 0x05

func init() {
	gob.Register(CapabilityReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x65),
		Command:      cc.CommandID(0x05),
		Version:      1,
	}, NewCapabilityReport)
}

func NewCapabilityReport() cc.Command {
	return &CapabilityReport{}
}

// <no value>
type CapabilityReport struct {
	ChannelId byte

	PropertyId uint16

	DeviceChannels byte

	MaxChannels byte
}

func (cmd CapabilityReport) CommandClassID() cc.CommandClassID {
	return 0x65
}

func (cmd CapabilityReport) CommandID() cc.CommandID {
	return CommandCapabilityReport
}

func (cmd CapabilityReport) CommandIDString() string {
	return "DMX_CAPABILITY_REPORT"
}

func (cmd *CapabilityReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ChannelId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.PropertyId = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.DeviceChannels = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.MaxChannels = payload[i]
	i++

	return nil
}

func (cmd *CapabilityReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.ChannelId)

	{
		buf := make([]byte, 2)
		binary.BigEndian.PutUint16(buf, cmd.PropertyId)
		payload = append(payload, buf...)
	}

	payload = append(payload, cmd.DeviceChannels)

	payload = append(payload, cmd.MaxChannels)

	return
}
