// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package zipgateway

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandGatewayLockSet cc.CommandID = 0x07

func init() {
	gob.Register(GatewayLockSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x5F),
		Command:      cc.CommandID(0x07),
		Version:      1,
	}, NewGatewayLockSet)
}

func NewGatewayLockSet() cc.Command {
	return &GatewayLockSet{}
}

// <no value>
type GatewayLockSet struct {
	Properties1 struct {
		Lock bool

		Show bool
	}
}

func (cmd GatewayLockSet) CommandClassID() cc.CommandClassID {
	return 0x5F
}

func (cmd GatewayLockSet) CommandID() cc.CommandID {
	return CommandGatewayLockSet
}

func (cmd GatewayLockSet) CommandIDString() string {
	return "GATEWAY_LOCK_SET"
}

func (cmd *GatewayLockSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.Lock = payload[i]&0x01 == 0x01

	cmd.Properties1.Show = payload[i]&0x02 == 0x02

	i += 1

	return nil
}

func (cmd *GatewayLockSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		if cmd.Properties1.Lock {
			val |= byte(0x01) // flip bits on
		} else {
			val &= ^byte(0x01) // flip bits off
		}

		if cmd.Properties1.Show {
			val |= byte(0x02) // flip bits on
		} else {
			val &= ^byte(0x02) // flip bits off
		}

		payload = append(payload, val)
	}

	return
}
