// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package zipgateway

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandGatewayModeSet cc.CommandID = 0x01

func init() {
	gob.Register(GatewayModeSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x5F),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewGatewayModeSet)
}

func NewGatewayModeSet() cc.Command {
	return &GatewayModeSet{}
}

// <no value>
type GatewayModeSet struct {
	Mode byte
}

func (cmd GatewayModeSet) CommandClassID() cc.CommandClassID {
	return 0x5F
}

func (cmd GatewayModeSet) CommandID() cc.CommandID {
	return CommandGatewayModeSet
}

func (cmd GatewayModeSet) CommandIDString() string {
	return "GATEWAY_MODE_SET"
}

func (cmd *GatewayModeSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Mode = payload[i]
	i++

	return nil
}

func (cmd *GatewayModeSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.Mode)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
