// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package zipgateway

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandGatewayModeReport cc.CommandID = 0x03

func init() {
	gob.Register(GatewayModeReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x5F),
		Command:      cc.CommandID(0x03),
		Version:      1,
	}, NewGatewayModeReport)
}

func NewGatewayModeReport() cc.Command {
	return &GatewayModeReport{}
}

// <no value>
type GatewayModeReport struct {
	Mode byte
}

func (cmd GatewayModeReport) CommandClassID() cc.CommandClassID {
	return 0x5F
}

func (cmd GatewayModeReport) CommandID() cc.CommandID {
	return CommandGatewayModeReport
}

func (cmd GatewayModeReport) CommandIDString() string {
	return "GATEWAY_MODE_REPORT"
}

func (cmd *GatewayModeReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Mode = payload[i]
	i++

	return nil
}

func (cmd *GatewayModeReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.Mode)

	return
}
