// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package zipgateway

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandGatewayModeGet cc.CommandID = 0x02

func init() {
	gob.Register(GatewayModeGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x5F),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewGatewayModeGet)
}

func NewGatewayModeGet() cc.Command {
	return &GatewayModeGet{}
}

// <no value>
type GatewayModeGet struct {
}

func (cmd GatewayModeGet) CommandClassID() cc.CommandClassID {
	return 0x5F
}

func (cmd GatewayModeGet) CommandID() cc.CommandID {
	return CommandGatewayModeGet
}

func (cmd GatewayModeGet) CommandIDString() string {
	return "GATEWAY_MODE_GET"
}

func (cmd *GatewayModeGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *GatewayModeGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
