// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package schedulev4

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandRemove cc.CommandID = 0x06

func init() {
	gob.Register(Remove{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x53),
		Command:      cc.CommandID(0x06),
		Version:      4,
	}, NewRemove)
}

func NewRemove() cc.Command {
	return &Remove{}
}

// <no value>
type Remove struct {
	ScheduleId byte

	ScheduleIdBlock byte
}

func (cmd Remove) CommandClassID() cc.CommandClassID {
	return 0x53
}

func (cmd Remove) CommandID() cc.CommandID {
	return CommandRemove
}

func (cmd Remove) CommandIDString() string {
	return "SCHEDULE_REMOVE"
}

func (cmd *Remove) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ScheduleId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ScheduleIdBlock = payload[i]
	i++

	return nil
}

func (cmd *Remove) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.ScheduleId)

	payload = append(payload, cmd.ScheduleIdBlock)

	return
}
