// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package schedulev4

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandSupportedCommandsGet cc.CommandID = 0x0A

func init() {
	gob.Register(SupportedCommandsGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x53),
		Command:      cc.CommandID(0x0A),
		Version:      4,
	}, NewSupportedCommandsGet)
}

func NewSupportedCommandsGet() cc.Command {
	return &SupportedCommandsGet{}
}

// <no value>
type SupportedCommandsGet struct {
	ScheduleIdBlock byte
}

func (cmd SupportedCommandsGet) CommandClassID() cc.CommandClassID {
	return 0x53
}

func (cmd SupportedCommandsGet) CommandID() cc.CommandID {
	return CommandSupportedCommandsGet
}

func (cmd SupportedCommandsGet) CommandIDString() string {
	return "SCHEDULE_SUPPORTED_COMMANDS_GET"
}

func (cmd *SupportedCommandsGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ScheduleIdBlock = payload[i]
	i++

	return nil
}

func (cmd *SupportedCommandsGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.ScheduleIdBlock)

	return
}
