// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package remoteassociation

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandConfigurationSet cc.CommandID = 0x01

func init() {
	gob.Register(ConfigurationSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x7D),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewConfigurationSet)
}

func NewConfigurationSet() cc.Command {
	return &ConfigurationSet{}
}

// <no value>
type ConfigurationSet struct {
	LocalGroupingIdentifier byte

	RemoteNodeid byte

	RemoteGroupingIdentifier byte
}

func (cmd ConfigurationSet) CommandClassID() cc.CommandClassID {
	return 0x7D
}

func (cmd ConfigurationSet) CommandID() cc.CommandID {
	return CommandConfigurationSet
}

func (cmd ConfigurationSet) CommandIDString() string {
	return "REMOTE_ASSOCIATION_CONFIGURATION_SET"
}

func (cmd *ConfigurationSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.LocalGroupingIdentifier = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.RemoteNodeid = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.RemoteGroupingIdentifier = payload[i]
	i++

	return nil
}

func (cmd *ConfigurationSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.LocalGroupingIdentifier)

	payload = append(payload, cmd.RemoteNodeid)

	payload = append(payload, cmd.RemoteGroupingIdentifier)

	return
}
