// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementinstallationmaintenancev2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandPriorityRouteSet cc.CommandID = 0x01

func init() {
	gob.Register(PriorityRouteSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x67),
		Command:      cc.CommandID(0x01),
		Version:      2,
	}, NewPriorityRouteSet)
}

func NewPriorityRouteSet() cc.Command {
	return &PriorityRouteSet{}
}

// <no value>
type PriorityRouteSet struct {
	Nodeid byte

	Repeater1 byte

	Repeater2 byte

	Repeater3 byte

	Repeater4 byte

	Speed byte
}

func (cmd PriorityRouteSet) CommandClassID() cc.CommandClassID {
	return 0x67
}

func (cmd PriorityRouteSet) CommandID() cc.CommandID {
	return CommandPriorityRouteSet
}

func (cmd PriorityRouteSet) CommandIDString() string {
	return "PRIORITY_ROUTE_SET"
}

func (cmd *PriorityRouteSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Nodeid = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Repeater1 = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Repeater2 = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Repeater3 = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Repeater4 = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Speed = payload[i]
	i++

	return nil
}

func (cmd *PriorityRouteSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.Nodeid)

	payload = append(payload, cmd.Repeater1)

	payload = append(payload, cmd.Repeater2)

	payload = append(payload, cmd.Repeater3)

	payload = append(payload, cmd.Repeater4)

	payload = append(payload, cmd.Speed)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
