// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementinstallationmaintenancev2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandPriorityRouteGet cc.CommandID = 0x02

func init() {
	gob.Register(PriorityRouteGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x67),
		Command:      cc.CommandID(0x02),
		Version:      2,
	}, NewPriorityRouteGet)
}

func NewPriorityRouteGet() cc.Command {
	return &PriorityRouteGet{}
}

// <no value>
type PriorityRouteGet struct {
	Nodeid byte
}

func (cmd PriorityRouteGet) CommandClassID() cc.CommandClassID {
	return 0x67
}

func (cmd PriorityRouteGet) CommandID() cc.CommandID {
	return CommandPriorityRouteGet
}

func (cmd PriorityRouteGet) CommandIDString() string {
	return "PRIORITY_ROUTE_GET"
}

func (cmd *PriorityRouteGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Nodeid = payload[i]
	i++

	return nil
}

func (cmd *PriorityRouteGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.Nodeid)

	return
}
