// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementinstallationmaintenancev2

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandStatisticsClear cc.CommandID = 0x06

func init() {
	gob.Register(StatisticsClear{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x67),
		Command:      cc.CommandID(0x06),
		Version:      2,
	}, NewStatisticsClear)
}

func NewStatisticsClear() cc.Command {
	return &StatisticsClear{}
}

// <no value>
type StatisticsClear struct {
}

func (cmd StatisticsClear) CommandClassID() cc.CommandClassID {
	return 0x67
}

func (cmd StatisticsClear) CommandID() cc.CommandID {
	return CommandStatisticsClear
}

func (cmd StatisticsClear) CommandIDString() string {
	return "STATISTICS_CLEAR"
}

func (cmd *StatisticsClear) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *StatisticsClear) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
