// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package hrvcontrol

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandModeSupportedReport cc.CommandID = 0x0B

func init() {
	gob.Register(ModeSupportedReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x39),
		Command:      cc.CommandID(0x0B),
		Version:      1,
	}, NewModeSupportedReport)
}

func NewModeSupportedReport() cc.Command {
	return &ModeSupportedReport{}
}

// <no value>
type ModeSupportedReport struct {
	Properties1 struct {
		ManualControlSupported byte
	}

	BitMask []byte
}

func (cmd ModeSupportedReport) CommandClassID() cc.CommandClassID {
	return 0x39
}

func (cmd ModeSupportedReport) CommandID() cc.CommandID {
	return CommandModeSupportedReport
}

func (cmd ModeSupportedReport) CommandIDString() string {
	return "HRV_CONTROL_MODE_SUPPORTED_REPORT"
}

func (cmd *ModeSupportedReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.ManualControlSupported = (payload[i] & 0x0F)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.BitMask = payload[i:]

	return nil
}

func (cmd *ModeSupportedReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		val |= (cmd.Properties1.ManualControlSupported) & byte(0x0F)

		payload = append(payload, val)
	}

	payload = append(payload, cmd.BitMask...)

	return
}
