// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package hrvcontrol

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandModeGet cc.CommandID = 0x02

func init() {
	gob.Register(ModeGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x39),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewModeGet)
}

func NewModeGet() cc.Command {
	return &ModeGet{}
}

// <no value>
type ModeGet struct {
}

func (cmd ModeGet) CommandClassID() cc.CommandClassID {
	return 0x39
}

func (cmd ModeGet) CommandID() cc.CommandID {
	return CommandModeGet
}

func (cmd ModeGet) CommandIDString() string {
	return "HRV_CONTROL_MODE_GET"
}

func (cmd *ModeGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *ModeGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
