// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package associationcommandconfiguration

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandConfigurationGet cc.CommandID = 0x04

func init() {
	gob.Register(ConfigurationGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x9B),
		Command:      cc.CommandID(0x04),
		Version:      1,
	}, NewConfigurationGet)
}

func NewConfigurationGet() cc.Command {
	return &ConfigurationGet{}
}

// <no value>
type ConfigurationGet struct {
	GroupingIdentifier byte

	NodeId byte
}

func (cmd ConfigurationGet) CommandClassID() cc.CommandClassID {
	return 0x9B
}

func (cmd ConfigurationGet) CommandID() cc.CommandID {
	return CommandConfigurationGet
}

func (cmd ConfigurationGet) CommandIDString() string {
	return "COMMAND_CONFIGURATION_GET"
}

func (cmd *ConfigurationGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.GroupingIdentifier = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NodeId = payload[i]
	i++

	return nil
}

func (cmd *ConfigurationGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.GroupingIdentifier)

	payload = append(payload, cmd.NodeId)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
