// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementinclusionv3

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandFailedNodeReplace cc.CommandID = 0x09

func init() {
	gob.Register(FailedNodeReplace{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x34),
		Command:      cc.CommandID(0x09),
		Version:      3,
	}, NewFailedNodeReplace)
}

func NewFailedNodeReplace() cc.Command {
	return &FailedNodeReplace{}
}

// <no value>
type FailedNodeReplace struct {
	SeqNo byte

	NodeId byte

	TxOptions []byte

	Mode byte
}

func (cmd FailedNodeReplace) CommandClassID() cc.CommandClassID {
	return 0x34
}

func (cmd FailedNodeReplace) CommandID() cc.CommandID {
	return CommandFailedNodeReplace
}

func (cmd FailedNodeReplace) CommandIDString() string {
	return "FAILED_NODE_REPLACE"
}

func (cmd *FailedNodeReplace) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NodeId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.TxOptions = payload[i:]

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Mode = payload[i]
	i++

	return nil
}

func (cmd *FailedNodeReplace) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	payload = append(payload, cmd.NodeId)

	payload = append(payload, cmd.TxOptions...)

	payload = append(payload, cmd.Mode)

	return
}
