// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementinclusionv3

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandIncludedNifReport cc.CommandID = 0x19

func init() {
	gob.Register(IncludedNifReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x34),
		Command:      cc.CommandID(0x19),
		Version:      3,
	}, NewIncludedNifReport)
}

func NewIncludedNifReport() cc.Command {
	return &IncludedNifReport{}
}

// <no value>
type IncludedNifReport struct {
	SeqNo byte

	Properties1 struct {
		DskLength byte
	}

	Dsk []byte
}

func (cmd IncludedNifReport) CommandClassID() cc.CommandClassID {
	return 0x34
}

func (cmd IncludedNifReport) CommandID() cc.CommandID {
	return CommandIncludedNifReport
}

func (cmd IncludedNifReport) CommandIDString() string {
	return "INCLUDED_NIF_REPORT"
}

func (cmd *IncludedNifReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.DskLength = (payload[i] & 0x1F)

	i += 1

	if len(payload) <= i {
		return nil // field is optional
	}

	{
		length := (payload[1+2]) & 0x1F
		cmd.Dsk = payload[i : i+int(length)]
		i += int(length)
	}

	return nil
}

func (cmd *IncludedNifReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	{
		var val byte

		val |= (cmd.Properties1.DskLength) & byte(0x1F)

		payload = append(payload, val)
	}

	if cmd.Dsk != nil && len(cmd.Dsk) > 0 {
		payload = append(payload, cmd.Dsk...)
	}

	return
}
