// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementinclusionv3

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandReturnRouteDeleteComplete cc.CommandID = 0x10

func init() {
	gob.Register(ReturnRouteDeleteComplete{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x34),
		Command:      cc.CommandID(0x10),
		Version:      3,
	}, NewReturnRouteDeleteComplete)
}

func NewReturnRouteDeleteComplete() cc.Command {
	return &ReturnRouteDeleteComplete{}
}

// <no value>
type ReturnRouteDeleteComplete struct {
	SeqNo byte

	Status byte
}

func (cmd ReturnRouteDeleteComplete) CommandClassID() cc.CommandClassID {
	return 0x34
}

func (cmd ReturnRouteDeleteComplete) CommandID() cc.CommandID {
	return CommandReturnRouteDeleteComplete
}

func (cmd ReturnRouteDeleteComplete) CommandIDString() string {
	return "RETURN_ROUTE_DELETE_COMPLETE"
}

func (cmd *ReturnRouteDeleteComplete) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Status = payload[i]
	i++

	return nil
}

func (cmd *ReturnRouteDeleteComplete) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	payload = append(payload, cmd.Status)

	return
}
