// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package networkmanagementinclusionv3

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandS2AdvancedJoinModeGet cc.CommandID = 0x17

func init() {
	gob.Register(S2AdvancedJoinModeGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x34),
		Command:      cc.CommandID(0x17),
		Version:      3,
	}, NewS2AdvancedJoinModeGet)
}

func NewS2AdvancedJoinModeGet() cc.Command {
	return &S2AdvancedJoinModeGet{}
}

// <no value>
type S2AdvancedJoinModeGet struct {
	SeqNo byte
}

func (cmd S2AdvancedJoinModeGet) CommandClassID() cc.CommandClassID {
	return 0x34
}

func (cmd S2AdvancedJoinModeGet) CommandID() cc.CommandID {
	return CommandS2AdvancedJoinModeGet
}

func (cmd S2AdvancedJoinModeGet) CommandIDString() string {
	return "S2_ADVANCED_JOIN_MODE_GET"
}

func (cmd *S2AdvancedJoinModeGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	return nil
}

func (cmd *S2AdvancedJoinModeGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	return
}
