// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package securitypanelzonesensor

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandCommandClassSecurityPanelZoneSensorInstalledReport cc.CommandID = 0x02

func init() {
	gob.Register(CommandClassSecurityPanelZoneSensorInstalledReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x2F),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewCommandClassSecurityPanelZoneSensorInstalledReport)
}

func NewCommandClassSecurityPanelZoneSensorInstalledReport() cc.Command {
	return &CommandClassSecurityPanelZoneSensorInstalledReport{}
}

// <no value>
type CommandClassSecurityPanelZoneSensorInstalledReport struct {
	ZoneNumber byte

	NumberOfSensors byte
}

func (cmd CommandClassSecurityPanelZoneSensorInstalledReport) CommandClassID() cc.CommandClassID {
	return 0x2F
}

func (cmd CommandClassSecurityPanelZoneSensorInstalledReport) CommandID() cc.CommandID {
	return CommandCommandClassSecurityPanelZoneSensorInstalledReport
}

func (cmd CommandClassSecurityPanelZoneSensorInstalledReport) CommandIDString() string {
	return "COMMAND_CLASS_SECURITY_PANEL_ZONE_SENSOR_INSTALLED_REPORT"
}

func (cmd *CommandClassSecurityPanelZoneSensorInstalledReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ZoneNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NumberOfSensors = payload[i]
	i++

	return nil
}

func (cmd *CommandClassSecurityPanelZoneSensorInstalledReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.ZoneNumber)

	payload = append(payload, cmd.NumberOfSensors)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
