// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package securitypanelzonesensor

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandStateReport cc.CommandID = 0x06

func init() {
	gob.Register(StateReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x2F),
		Command:      cc.CommandID(0x06),
		Version:      1,
	}, NewStateReport)
}

func NewStateReport() cc.Command {
	return &StateReport{}
}

// <no value>
type StateReport struct {
	ZoneNumber byte

	SensorNumber byte

	ZwaveAlarmType byte

	ZwaveAlarmEvent byte

	EventParameters byte
}

func (cmd StateReport) CommandClassID() cc.CommandClassID {
	return 0x2F
}

func (cmd StateReport) CommandID() cc.CommandID {
	return CommandStateReport
}

func (cmd StateReport) CommandIDString() string {
	return "SECURITY_PANEL_ZONE_SENSOR_STATE_REPORT"
}

func (cmd *StateReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ZoneNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SensorNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ZwaveAlarmType = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ZwaveAlarmEvent = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.EventParameters = payload[i]
	i++

	return nil
}

func (cmd *StateReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.ZoneNumber)

	payload = append(payload, cmd.SensorNumber)

	payload = append(payload, cmd.ZwaveAlarmType)

	payload = append(payload, cmd.ZwaveAlarmEvent)

	payload = append(payload, cmd.EventParameters)

	return
}
