// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package nodeprovisioning

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandDelete cc.CommandID = 0x02

func init() {
	gob.Register(Delete{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x78),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewDelete)
}

func NewDelete() cc.Command {
	return &Delete{}
}

// <no value>
type Delete struct {
	SeqNo byte

	Properties1 struct {
		DskLength byte
	}

	Dsk []byte
}

func (cmd Delete) CommandClassID() cc.CommandClassID {
	return 0x78
}

func (cmd Delete) CommandID() cc.CommandID {
	return CommandDelete
}

func (cmd Delete) CommandIDString() string {
	return "NODE_PROVISIONING_DELETE"
}

func (cmd *Delete) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.DskLength = (payload[i] & 0x1F)

	i += 1

	if len(payload) <= i {
		return nil // field is optional
	}

	{
		length := (payload[1+2]) & 0x1F
		cmd.Dsk = payload[i : i+int(length)]
		i += int(length)
	}

	return nil
}

func (cmd *Delete) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	{
		var val byte

		val |= (cmd.Properties1.DskLength) & byte(0x1F)

		payload = append(payload, val)
	}

	if cmd.Dsk != nil && len(cmd.Dsk) > 0 {
		payload = append(payload, cmd.Dsk...)
	}

	return
}
