// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package nodeprovisioning

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandListIterationGet cc.CommandID = 0x03

func init() {
	gob.Register(ListIterationGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x78),
		Command:      cc.CommandID(0x03),
		Version:      1,
	}, NewListIterationGet)
}

func NewListIterationGet() cc.Command {
	return &ListIterationGet{}
}

// <no value>
type ListIterationGet struct {
	SeqNo byte

	RemainingCounter byte
}

func (cmd ListIterationGet) CommandClassID() cc.CommandClassID {
	return 0x78
}

func (cmd ListIterationGet) CommandID() cc.CommandID {
	return CommandListIterationGet
}

func (cmd ListIterationGet) CommandIDString() string {
	return "NODE_PROVISIONING_LIST_ITERATION_GET"
}

func (cmd *ListIterationGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.RemainingCounter = payload[i]
	i++

	return nil
}

func (cmd *ListIterationGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SeqNo)

	payload = append(payload, cmd.RemainingCounter)

	return
}
