// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package zip6lowpan

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandLowpanFirstFragment cc.CommandID = 0xC0

func init() {
	gob.Register(LowpanFirstFragment{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x4F),
		Command:      cc.CommandID(0xC0),
		Version:      1,
	}, NewLowpanFirstFragment)
}

func NewLowpanFirstFragment() cc.Command {
	return &LowpanFirstFragment{}
}

// <no value>
type LowpanFirstFragment struct {
	Properties1 struct {
		DatagramSize1 byte
	}

	DatagramSize2 byte

	DatagramTag byte

	Payload []byte
}

func (cmd LowpanFirstFragment) CommandClassID() cc.CommandClassID {
	return 0x4F
}

func (cmd LowpanFirstFragment) CommandID() cc.CommandID {
	return CommandLowpanFirstFragment
}

func (cmd LowpanFirstFragment) CommandIDString() string {
	return "LOWPAN_FIRST_FRAGMENT"
}

func (cmd *LowpanFirstFragment) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.DatagramSize1 = (payload[i] & 0x07)

	i += 1

	if len(payload) <= i {
		return nil // field is optional
	}

	cmd.DatagramSize2 = payload[i]
	i++

	if len(payload) <= i {
		return nil // field is optional
	}

	cmd.DatagramTag = payload[i]
	i++

	if len(payload) <= i {
		return nil
	}

	cmd.Payload = payload[i:]

	return nil
}

func (cmd *LowpanFirstFragment) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		val |= (cmd.Properties1.DatagramSize1) & byte(0x07)

		payload = append(payload, val)
	}

	payload = append(payload, cmd.DatagramSize2)

	payload = append(payload, cmd.DatagramTag)

	payload = append(payload, cmd.Payload...)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
