// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package zipnaming

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandLocationReport cc.CommandID = 0x06

func init() {
	gob.Register(LocationReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x68),
		Command:      cc.CommandID(0x06),
		Version:      1,
	}, NewLocationReport)
}

func NewLocationReport() cc.Command {
	return &LocationReport{}
}

// <no value>
type LocationReport struct {
	Location []byte
}

func (cmd LocationReport) CommandClassID() cc.CommandClassID {
	return 0x68
}

func (cmd LocationReport) CommandID() cc.CommandID {
	return CommandLocationReport
}

func (cmd LocationReport) CommandIDString() string {
	return "ZIP_NAMING_LOCATION_REPORT"
}

func (cmd *LocationReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return nil
	}

	cmd.Location = payload[i:]

	return nil
}

func (cmd *LocationReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.Location...)

	return
}
