// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package zipnaming

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandNameSet cc.CommandID = 0x01

func init() {
	gob.Register(NameSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x68),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewNameSet)
}

func NewNameSet() cc.Command {
	return &NameSet{}
}

// <no value>
type NameSet struct {
	Name []byte
}

func (cmd NameSet) CommandClassID() cc.CommandClassID {
	return 0x68
}

func (cmd NameSet) CommandID() cc.CommandID {
	return CommandNameSet
}

func (cmd NameSet) CommandIDString() string {
	return "ZIP_NAMING_NAME_SET"
}

func (cmd *NameSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return nil
	}

	cmd.Name = payload[i:]

	return nil
}

func (cmd *NameSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.Name...)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
