// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package applicationcapability

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandCommandClassNotSupported cc.CommandID = 0x01

func init() {
	gob.Register(CommandClassNotSupported{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x57),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewCommandClassNotSupported)
}

func NewCommandClassNotSupported() cc.Command {
	return &CommandClassNotSupported{}
}

// <no value>
type CommandClassNotSupported struct {
	Properties1 struct {
		Dynamic bool
	}

	OffendingCommandClass byte

	OffendingCommand byte
}

func (cmd CommandClassNotSupported) CommandClassID() cc.CommandClassID {
	return 0x57
}

func (cmd CommandClassNotSupported) CommandID() cc.CommandID {
	return CommandCommandClassNotSupported
}

func (cmd CommandClassNotSupported) CommandIDString() string {
	return "COMMAND_COMMAND_CLASS_NOT_SUPPORTED"
}

func (cmd *CommandClassNotSupported) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.Dynamic = payload[i]&0x80 == 0x80

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.OffendingCommandClass = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.OffendingCommand = payload[i]
	i++

	return nil
}

func (cmd *CommandClassNotSupported) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		if cmd.Properties1.Dynamic {
			val |= byte(0x80) // flip bits on
		} else {
			val &= ^byte(0x80) // flip bits off
		}

		payload = append(payload, val)
	}

	payload = append(payload, cmd.OffendingCommandClass)

	payload = append(payload, cmd.OffendingCommand)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
