// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package powerlevel

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandTestNodeGet cc.CommandID = 0x05

func init() {
	gob.Register(TestNodeGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x73),
		Command:      cc.CommandID(0x05),
		Version:      1,
	}, NewTestNodeGet)
}

func NewTestNodeGet() cc.Command {
	return &TestNodeGet{}
}

// <no value>
type TestNodeGet struct {
}

func (cmd TestNodeGet) CommandClassID() cc.CommandClassID {
	return 0x73
}

func (cmd TestNodeGet) CommandID() cc.CommandID {
	return CommandTestNodeGet
}

func (cmd TestNodeGet) CommandIDString() string {
	return "POWERLEVEL_TEST_NODE_GET"
}

func (cmd *TestNodeGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *TestNodeGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
