// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package controllerreplication

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandCtrlReplicationTransferGroup cc.CommandID = 0x31

func init() {
	gob.Register(CtrlReplicationTransferGroup{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x21),
		Command:      cc.CommandID(0x31),
		Version:      1,
	}, NewCtrlReplicationTransferGroup)
}

func NewCtrlReplicationTransferGroup() cc.Command {
	return &CtrlReplicationTransferGroup{}
}

// <no value>
type CtrlReplicationTransferGroup struct {
	SequenceNumber byte

	GroupId byte

	NodeId byte
}

func (cmd CtrlReplicationTransferGroup) CommandClassID() cc.CommandClassID {
	return 0x21
}

func (cmd CtrlReplicationTransferGroup) CommandID() cc.CommandID {
	return CommandCtrlReplicationTransferGroup
}

func (cmd CtrlReplicationTransferGroup) CommandIDString() string {
	return "CTRL_REPLICATION_TRANSFER_GROUP"
}

func (cmd *CtrlReplicationTransferGroup) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SequenceNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.GroupId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NodeId = payload[i]
	i++

	return nil
}

func (cmd *CtrlReplicationTransferGroup) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SequenceNumber)

	payload = append(payload, cmd.GroupId)

	payload = append(payload, cmd.NodeId)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
