// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package controllerreplication

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandCtrlReplicationTransferScene cc.CommandID = 0x33

func init() {
	gob.Register(CtrlReplicationTransferScene{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x21),
		Command:      cc.CommandID(0x33),
		Version:      1,
	}, NewCtrlReplicationTransferScene)
}

func NewCtrlReplicationTransferScene() cc.Command {
	return &CtrlReplicationTransferScene{}
}

// <no value>
type CtrlReplicationTransferScene struct {
	SequenceNumber byte

	SceneId byte

	NodeId byte

	Level byte
}

func (cmd CtrlReplicationTransferScene) CommandClassID() cc.CommandClassID {
	return 0x21
}

func (cmd CtrlReplicationTransferScene) CommandID() cc.CommandID {
	return CommandCtrlReplicationTransferScene
}

func (cmd CtrlReplicationTransferScene) CommandIDString() string {
	return "CTRL_REPLICATION_TRANSFER_SCENE"
}

func (cmd *CtrlReplicationTransferScene) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SequenceNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SceneId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NodeId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level = payload[i]
	i++

	return nil
}

func (cmd *CtrlReplicationTransferScene) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SequenceNumber)

	payload = append(payload, cmd.SceneId)

	payload = append(payload, cmd.NodeId)

	payload = append(payload, cmd.Level)

	return
}
