// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package metertblmonitor

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandMeterTblTablePointAdmNoGet cc.CommandID = 0x01

func init() {
	gob.Register(MeterTblTablePointAdmNoGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x3D),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewMeterTblTablePointAdmNoGet)
}

func NewMeterTblTablePointAdmNoGet() cc.Command {
	return &MeterTblTablePointAdmNoGet{}
}

// <no value>
type MeterTblTablePointAdmNoGet struct {
}

func (cmd MeterTblTablePointAdmNoGet) CommandClassID() cc.CommandClassID {
	return 0x3D
}

func (cmd MeterTblTablePointAdmNoGet) CommandID() cc.CommandID {
	return CommandMeterTblTablePointAdmNoGet
}

func (cmd MeterTblTablePointAdmNoGet) CommandIDString() string {
	return "METER_TBL_TABLE_POINT_ADM_NO_GET"
}

func (cmd *MeterTblTablePointAdmNoGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *MeterTblTablePointAdmNoGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
