// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package metertblmonitor

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandMeterTblStatusDepthGet cc.CommandID = 0x09

func init() {
	gob.Register(MeterTblStatusDepthGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x3D),
		Command:      cc.CommandID(0x09),
		Version:      1,
	}, NewMeterTblStatusDepthGet)
}

func NewMeterTblStatusDepthGet() cc.Command {
	return &MeterTblStatusDepthGet{}
}

// <no value>
type MeterTblStatusDepthGet struct {
	StatusEventLogDepth byte
}

func (cmd MeterTblStatusDepthGet) CommandClassID() cc.CommandClassID {
	return 0x3D
}

func (cmd MeterTblStatusDepthGet) CommandID() cc.CommandID {
	return CommandMeterTblStatusDepthGet
}

func (cmd MeterTblStatusDepthGet) CommandIDString() string {
	return "METER_TBL_STATUS_DEPTH_GET"
}

func (cmd *MeterTblStatusDepthGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.StatusEventLogDepth = payload[i]
	i++

	return nil
}

func (cmd *MeterTblStatusDepthGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.StatusEventLogDepth)

	return
}
