// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package remoteassociationactivate

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandRemoteAssociationActivate cc.CommandID = 0x01

func init() {
	gob.Register(RemoteAssociationActivate{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x7C),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewRemoteAssociationActivate)
}

func NewRemoteAssociationActivate() cc.Command {
	return &RemoteAssociationActivate{}
}

// <no value>
type RemoteAssociationActivate struct {
	GroupingIdentifier byte
}

func (cmd RemoteAssociationActivate) CommandClassID() cc.CommandClassID {
	return 0x7C
}

func (cmd RemoteAssociationActivate) CommandID() cc.CommandID {
	return CommandRemoteAssociationActivate
}

func (cmd RemoteAssociationActivate) CommandIDString() string {
	return "REMOTE_ASSOCIATION_ACTIVATE"
}

func (cmd *RemoteAssociationActivate) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.GroupingIdentifier = payload[i]
	i++

	return nil
}

func (cmd *RemoteAssociationActivate) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.GroupingIdentifier)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
