// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package metertblmonitorv2

import (
	"encoding/binary"
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandMeterTblStatusSupportedReport cc.CommandID = 0x08

func init() {
	gob.Register(MeterTblStatusSupportedReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x3D),
		Command:      cc.CommandID(0x08),
		Version:      2,
	}, NewMeterTblStatusSupportedReport)
}

func NewMeterTblStatusSupportedReport() cc.Command {
	return &MeterTblStatusSupportedReport{}
}

// <no value>
type MeterTblStatusSupportedReport struct {
	SupportedOperatingStatus uint32

	StatusEventLogDepth byte
}

func (cmd MeterTblStatusSupportedReport) CommandClassID() cc.CommandClassID {
	return 0x3D
}

func (cmd MeterTblStatusSupportedReport) CommandID() cc.CommandID {
	return CommandMeterTblStatusSupportedReport
}

func (cmd MeterTblStatusSupportedReport) CommandIDString() string {
	return "METER_TBL_STATUS_SUPPORTED_REPORT"
}

func (cmd *MeterTblStatusSupportedReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SupportedOperatingStatus = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.StatusEventLogDepth = payload[i]
	i++

	return nil
}

func (cmd *MeterTblStatusSupportedReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		buf := make([]byte, 4)
		binary.BigEndian.PutUint32(buf, cmd.SupportedOperatingStatus)
		if buf[0] != 0 {
			return nil, errors.New("BIT_24 value overflow")
		}
		payload = append(payload, buf[1:4]...)
	}

	payload = append(payload, cmd.StatusEventLogDepth)

	return
}
