// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package metertblmonitorv2

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandMeterTblStatusSupportedGet cc.CommandID = 0x07

func init() {
	gob.Register(MeterTblStatusSupportedGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x3D),
		Command:      cc.CommandID(0x07),
		Version:      2,
	}, NewMeterTblStatusSupportedGet)
}

func NewMeterTblStatusSupportedGet() cc.Command {
	return &MeterTblStatusSupportedGet{}
}

// <no value>
type MeterTblStatusSupportedGet struct {
}

func (cmd MeterTblStatusSupportedGet) CommandClassID() cc.CommandClassID {
	return 0x3D
}

func (cmd MeterTblStatusSupportedGet) CommandID() cc.CommandID {
	return CommandMeterTblStatusSupportedGet
}

func (cmd MeterTblStatusSupportedGet) CommandIDString() string {
	return "METER_TBL_STATUS_SUPPORTED_GET"
}

func (cmd *MeterTblStatusSupportedGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *MeterTblStatusSupportedGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
