// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package metertblmonitorv2

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandMeterTblTableIdReport cc.CommandID = 0x04

func init() {
	gob.Register(MeterTblTableIdReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x3D),
		Command:      cc.CommandID(0x04),
		Version:      2,
	}, NewMeterTblTableIdReport)
}

func NewMeterTblTableIdReport() cc.Command {
	return &MeterTblTableIdReport{}
}

// <no value>
type MeterTblTableIdReport struct {
	Properties1 struct {
		NumberOfCharacters byte
	}

	MeterIdCharacter []byte
}

func (cmd MeterTblTableIdReport) CommandClassID() cc.CommandClassID {
	return 0x3D
}

func (cmd MeterTblTableIdReport) CommandID() cc.CommandID {
	return CommandMeterTblTableIdReport
}

func (cmd MeterTblTableIdReport) CommandIDString() string {
	return "METER_TBL_TABLE_ID_REPORT"
}

func (cmd *MeterTblTableIdReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.NumberOfCharacters = (payload[i] & 0x1F)

	i += 1

	if len(payload) <= i {
		return nil // field is optional
	}

	{
		length := (payload[0+2]) & 0x1F
		cmd.MeterIdCharacter = payload[i : i+int(length)]
		i += int(length)
	}

	return nil
}

func (cmd *MeterTblTableIdReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		val |= (cmd.Properties1.NumberOfCharacters) & byte(0x1F)

		payload = append(payload, val)
	}

	if cmd.MeterIdCharacter != nil && len(cmd.MeterIdCharacter) > 0 {
		payload = append(payload, cmd.MeterIdCharacter...)
	}

	return
}
