// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package ratetblmonitor

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandRateTblSupportedGet cc.CommandID = 0x01

func init() {
	gob.Register(RateTblSupportedGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x49),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewRateTblSupportedGet)
}

func NewRateTblSupportedGet() cc.Command {
	return &RateTblSupportedGet{}
}

// <no value>
type RateTblSupportedGet struct {
}

func (cmd RateTblSupportedGet) CommandClassID() cc.CommandClassID {
	return 0x49
}

func (cmd RateTblSupportedGet) CommandID() cc.CommandID {
	return CommandRateTblSupportedGet
}

func (cmd RateTblSupportedGet) CommandIDString() string {
	return "RATE_TBL_SUPPORTED_GET"
}

func (cmd *RateTblSupportedGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *RateTblSupportedGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
