// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package ratetblmonitor

import (
	"encoding/binary"
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandRateTblHistoricalDataReport cc.CommandID = 0x0A

func init() {
	gob.Register(RateTblHistoricalDataReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x49),
		Command:      cc.CommandID(0x0A),
		Version:      1,
	}, NewRateTblHistoricalDataReport)
}

func NewRateTblHistoricalDataReport() cc.Command {
	return &RateTblHistoricalDataReport{}
}

// <no value>
type RateTblHistoricalDataReport struct {
	ReportsToFollow byte

	RateParameterSetId byte

	Dataset uint32

	Year uint16

	Month byte

	Day byte

	HourLocalTime byte

	MinuteLocalTime byte

	SecondLocalTime byte

	Vg []RateTblHistoricalDataReportVg
}

type RateTblHistoricalDataReportVg struct {
	Properties1 struct {
		HistoricalScale byte

		HistoricalPrecision byte
	}

	HistoricalValue uint32
}

func (cmd RateTblHistoricalDataReport) CommandClassID() cc.CommandClassID {
	return 0x49
}

func (cmd RateTblHistoricalDataReport) CommandID() cc.CommandID {
	return CommandRateTblHistoricalDataReport
}

func (cmd RateTblHistoricalDataReport) CommandIDString() string {
	return "RATE_TBL_HISTORICAL_DATA_REPORT"
}

func (cmd *RateTblHistoricalDataReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ReportsToFollow = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.RateParameterSetId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Dataset = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Year = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Month = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Day = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.HourLocalTime = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.MinuteLocalTime = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SecondLocalTime = payload[i]
	i++

	for i < len(payload) {

		vg := RateTblHistoricalDataReportVg{}

		if len(payload) <= i {
			return errors.New("slice index out of bounds")
		}

		vg.Properties1.HistoricalScale = (payload[i] & 0x1F)

		vg.Properties1.HistoricalPrecision = (payload[i] & 0xE0) >> 5

		i += 1

		if len(payload) <= i {
			return errors.New("slice index out of bounds")
		}

		historicalValue := binary.BigEndian.Uint32(payload[i : i+4])
		i += 4

		// struct byte fields are assigned to the variant group when computed

		vg.HistoricalValue = historicalValue

		cmd.Vg = append(cmd.Vg, vg)
	}

	return nil
}

func (cmd *RateTblHistoricalDataReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.ReportsToFollow)

	payload = append(payload, cmd.RateParameterSetId)

	{
		buf := make([]byte, 4)
		binary.BigEndian.PutUint32(buf, cmd.Dataset)
		if buf[0] != 0 {
			return nil, errors.New("BIT_24 value overflow")
		}
		payload = append(payload, buf[1:4]...)
	}

	{
		buf := make([]byte, 2)
		binary.BigEndian.PutUint16(buf, cmd.Year)
		payload = append(payload, buf...)
	}

	payload = append(payload, cmd.Month)

	payload = append(payload, cmd.Day)

	payload = append(payload, cmd.HourLocalTime)

	payload = append(payload, cmd.MinuteLocalTime)

	payload = append(payload, cmd.SecondLocalTime)

	for _, vg := range cmd.Vg {

		{
			var val byte

			val |= (vg.Properties1.HistoricalScale) & byte(0x1F)

			val |= (vg.Properties1.HistoricalPrecision << byte(5)) & byte(0xE0)

			payload = append(payload, val)
		}

		{
			buf := make([]byte, 4)
			binary.BigEndian.PutUint32(buf, vg.HistoricalValue)
			payload = append(payload, buf...)
		}

	}

	return
}
