// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package mtpwindowcovering

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandMoveToPositionSet cc.CommandID = 0x01

func init() {
	gob.Register(MoveToPositionSet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x51),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewMoveToPositionSet)
}

func NewMoveToPositionSet() cc.Command {
	return &MoveToPositionSet{}
}

// <no value>
type MoveToPositionSet struct {
	Value byte
}

func (cmd MoveToPositionSet) CommandClassID() cc.CommandClassID {
	return 0x51
}

func (cmd MoveToPositionSet) CommandID() cc.CommandID {
	return CommandMoveToPositionSet
}

func (cmd MoveToPositionSet) CommandIDString() string {
	return "MOVE_TO_POSITION_SET"
}

func (cmd *MoveToPositionSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Value = payload[i]
	i++

	return nil
}

func (cmd *MoveToPositionSet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.Value)

	return
}
