// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package mtpwindowcovering

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandMoveToPositionGet cc.CommandID = 0x02

func init() {
	gob.Register(MoveToPositionGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x51),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewMoveToPositionGet)
}

func NewMoveToPositionGet() cc.Command {
	return &MoveToPositionGet{}
}

// <no value>
type MoveToPositionGet struct {
}

func (cmd MoveToPositionGet) CommandClassID() cc.CommandClassID {
	return 0x51
}

func (cmd MoveToPositionGet) CommandID() cc.CommandID {
	return CommandMoveToPositionGet
}

func (cmd MoveToPositionGet) CommandIDString() string {
	return "MOVE_TO_POSITION_GET"
}

func (cmd *MoveToPositionGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *MoveToPositionGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
