// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package dcpconfig

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandDcpListSupportedGet cc.CommandID = 0x01

func init() {
	gob.Register(DcpListSupportedGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x3A),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewDcpListSupportedGet)
}

func NewDcpListSupportedGet() cc.Command {
	return &DcpListSupportedGet{}
}

// <no value>
type DcpListSupportedGet struct {
}

func (cmd DcpListSupportedGet) CommandClassID() cc.CommandClassID {
	return 0x3A
}

func (cmd DcpListSupportedGet) CommandID() cc.CommandID {
	return CommandDcpListSupportedGet
}

func (cmd DcpListSupportedGet) CommandIDString() string {
	return "DCP_LIST_SUPPORTED_GET"
}

func (cmd *DcpListSupportedGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *DcpListSupportedGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
