// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package dcpconfig

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandDcpListSupportedReport cc.CommandID = 0x02

func init() {
	gob.Register(DcpListSupportedReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x3A),
		Command:      cc.CommandID(0x02),
		Version:      1,
	}, NewDcpListSupportedReport)
}

func NewDcpListSupportedReport() cc.Command {
	return &DcpListSupportedReport{}
}

// <no value>
type DcpListSupportedReport struct {
	DcpListSize byte

	FreeDcpListEntries byte
}

func (cmd DcpListSupportedReport) CommandClassID() cc.CommandClassID {
	return 0x3A
}

func (cmd DcpListSupportedReport) CommandID() cc.CommandID {
	return CommandDcpListSupportedReport
}

func (cmd DcpListSupportedReport) CommandIDString() string {
	return "DCP_LIST_SUPPORTED_REPORT"
}

func (cmd *DcpListSupportedReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.DcpListSize = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.FreeDcpListEntries = payload[i]
	i++

	return nil
}

func (cmd *DcpListSupportedReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.DcpListSize)

	payload = append(payload, cmd.FreeDcpListEntries)

	return
}
