// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package metertblmonitorv3

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandMeterTblTableCapabilityGet cc.CommandID = 0x05

func init() {
	gob.Register(MeterTblTableCapabilityGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x3D),
		Command:      cc.CommandID(0x05),
		Version:      3,
	}, NewMeterTblTableCapabilityGet)
}

func NewMeterTblTableCapabilityGet() cc.Command {
	return &MeterTblTableCapabilityGet{}
}

// <no value>
type MeterTblTableCapabilityGet struct {
}

func (cmd MeterTblTableCapabilityGet) CommandClassID() cc.CommandClassID {
	return 0x3D
}

func (cmd MeterTblTableCapabilityGet) CommandID() cc.CommandID {
	return CommandMeterTblTableCapabilityGet
}

func (cmd MeterTblTableCapabilityGet) CommandIDString() string {
	return "METER_TBL_TABLE_CAPABILITY_GET"
}

func (cmd *MeterTblTableCapabilityGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *MeterTblTableCapabilityGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
