// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package tarifftblmonitor

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandTariffTblSupplierGet cc.CommandID = 0x01

func init() {
	gob.Register(TariffTblSupplierGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x4B),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewTariffTblSupplierGet)
}

func NewTariffTblSupplierGet() cc.Command {
	return &TariffTblSupplierGet{}
}

// <no value>
type TariffTblSupplierGet struct {
}

func (cmd TariffTblSupplierGet) CommandClassID() cc.CommandClassID {
	return 0x4B
}

func (cmd TariffTblSupplierGet) CommandID() cc.CommandID {
	return CommandTariffTblSupplierGet
}

func (cmd TariffTblSupplierGet) CommandIDString() string {
	return "TARIFF_TBL_SUPPLIER_GET"
}

func (cmd *TariffTblSupplierGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *TariffTblSupplierGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
