// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package inclusioncontroller

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandInitiate cc.CommandID = 0x01

func init() {
	gob.Register(Initiate{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x74),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewInitiate)
}

func NewInitiate() cc.Command {
	return &Initiate{}
}

// <no value>
type Initiate struct {
	NodeId byte

	StepId byte
}

func (cmd Initiate) CommandClassID() cc.CommandClassID {
	return 0x74
}

func (cmd Initiate) CommandID() cc.CommandID {
	return CommandInitiate
}

func (cmd Initiate) CommandIDString() string {
	return "INITIATE"
}

func (cmd *Initiate) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NodeId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.StepId = payload[i]
	i++

	return nil
}

func (cmd *Initiate) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.NodeId)

	payload = append(payload, cmd.StepId)

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
