// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package scheduleentrylockv3

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandDailyRepeatingReport cc.CommandID = 0x0F

func init() {
	gob.Register(DailyRepeatingReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x4E),
		Command:      cc.CommandID(0x0F),
		Version:      3,
	}, NewDailyRepeatingReport)
}

func NewDailyRepeatingReport() cc.Command {
	return &DailyRepeatingReport{}
}

// <no value>
type DailyRepeatingReport struct {
	UserIdentifier byte

	ScheduleSlotId byte

	WeekDayBitmask byte

	StartHour byte

	StartMinute byte

	DurationHour byte

	DurationMinute byte
}

func (cmd DailyRepeatingReport) CommandClassID() cc.CommandClassID {
	return 0x4E
}

func (cmd DailyRepeatingReport) CommandID() cc.CommandID {
	return CommandDailyRepeatingReport
}

func (cmd DailyRepeatingReport) CommandIDString() string {
	return "SCHEDULE_ENTRY_LOCK_DAILY_REPEATING_REPORT"
}

func (cmd *DailyRepeatingReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.UserIdentifier = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ScheduleSlotId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.WeekDayBitmask = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.StartHour = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.StartMinute = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.DurationHour = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.DurationMinute = payload[i]
	i++

	return nil
}

func (cmd *DailyRepeatingReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.UserIdentifier)

	payload = append(payload, cmd.ScheduleSlotId)

	payload = append(payload, cmd.WeekDayBitmask)

	payload = append(payload, cmd.StartHour)

	payload = append(payload, cmd.StartMinute)

	payload = append(payload, cmd.DurationHour)

	payload = append(payload, cmd.DurationMinute)

	return
}
