// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package irrigation

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandSystemShutoff cc.CommandID = 0x12

func init() {
	gob.Register(SystemShutoff{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x6B),
		Command:      cc.CommandID(0x12),
		Version:      1,
	}, NewSystemShutoff)
}

func NewSystemShutoff() cc.Command {
	return &SystemShutoff{}
}

// <no value>
type SystemShutoff struct {
	Duration byte
}

func (cmd SystemShutoff) CommandClassID() cc.CommandClassID {
	return 0x6B
}

func (cmd SystemShutoff) CommandID() cc.CommandID {
	return CommandSystemShutoff
}

func (cmd SystemShutoff) CommandIDString() string {
	return "IRRIGATION_SYSTEM_SHUTOFF"
}

func (cmd *SystemShutoff) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Duration = payload[i]
	i++

	return nil
}

func (cmd *SystemShutoff) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.Duration)

	return
}
