// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package irrigation

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandSystemInfoGet cc.CommandID = 0x01

func init() {
	gob.Register(SystemInfoGet{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x6B),
		Command:      cc.CommandID(0x01),
		Version:      1,
	}, NewSystemInfoGet)
}

func NewSystemInfoGet() cc.Command {
	return &SystemInfoGet{}
}

// <no value>
type SystemInfoGet struct {
}

func (cmd SystemInfoGet) CommandClassID() cc.CommandClassID {
	return 0x6B
}

func (cmd SystemInfoGet) CommandID() cc.CommandID {
	return CommandSystemInfoGet
}

func (cmd SystemInfoGet) CommandIDString() string {
	return "IRRIGATION_SYSTEM_INFO_GET"
}

func (cmd *SystemInfoGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *SystemInfoGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}

func Noop() {
	// does nothing, just here to allow
	// consumers to invoke the init function
}
