// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package irrigation

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandValveInfoReport cc.CommandID = 0x09

func init() {
	gob.Register(ValveInfoReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x6B),
		Command:      cc.CommandID(0x09),
		Version:      1,
	}, NewValveInfoReport)
}

func NewValveInfoReport() cc.Command {
	return &ValveInfoReport{}
}

// <no value>
type ValveInfoReport struct {
	Properties1 struct {
		Master bool

		Connected bool
	}

	ValveId byte

	NominalCurrent byte

	ValveErrorStatus []byte
}

func (cmd ValveInfoReport) CommandClassID() cc.CommandClassID {
	return 0x6B
}

func (cmd ValveInfoReport) CommandID() cc.CommandID {
	return CommandValveInfoReport
}

func (cmd ValveInfoReport) CommandIDString() string {
	return "IRRIGATION_VALVE_INFO_REPORT"
}

func (cmd *ValveInfoReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.Master = payload[i]&0x01 == 0x01

	cmd.Properties1.Connected = payload[i]&0x02 == 0x02

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ValveId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NominalCurrent = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ValveErrorStatus = payload[i:]

	return nil
}

func (cmd *ValveInfoReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		if cmd.Properties1.Master {
			val |= byte(0x01) // flip bits on
		} else {
			val &= ^byte(0x01) // flip bits off
		}

		if cmd.Properties1.Connected {
			val |= byte(0x02) // flip bits on
		} else {
			val &= ^byte(0x02) // flip bits off
		}

		payload = append(payload, val)
	}

	payload = append(payload, cmd.ValveId)

	payload = append(payload, cmd.NominalCurrent)

	payload = append(payload, cmd.ValveErrorStatus...)

	return
}
