// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package irrigation

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandValveTableRun cc.CommandID = 0x11

func init() {
	gob.Register(ValveTableRun{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x6B),
		Command:      cc.CommandID(0x11),
		Version:      1,
	}, NewValveTableRun)
}

func NewValveTableRun() cc.Command {
	return &ValveTableRun{}
}

// <no value>
type ValveTableRun struct {
	ValveTableId []byte
}

func (cmd ValveTableRun) CommandClassID() cc.CommandClassID {
	return 0x6B
}

func (cmd ValveTableRun) CommandID() cc.CommandID {
	return CommandValveTableRun
}

func (cmd ValveTableRun) CommandIDString() string {
	return "IRRIGATION_VALVE_TABLE_RUN"
}

func (cmd *ValveTableRun) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return nil
	}

	cmd.ValveTableId = payload[i:]

	return nil
}

func (cmd *ValveTableRun) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.ValveTableId...)

	return
}
